name: 03-build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [typescript, rust, go, java]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js
        if: ${{ matrix.target == 'typescript' }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18
          cache: npm

      - name: Build TypeScript workspaces
        if: ${{ matrix.target == 'typescript' }}
        run: |
          npm install
          npm run build --workspaces --if-present

      - name: Setup Rust
        if: ${{ matrix.target == 'rust' }}
        uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # stable
        with:
          components: clippy

      - name: Cargo build
        if: ${{ matrix.target == 'rust' }}
        run: cargo build --workspace --all-features

      - name: Setup Go
        if: ${{ matrix.target == 'go' }}
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 1.21

      - name: Go build
        if: ${{ matrix.target == 'go' }}
        run: go build ./...
        working-directory: services

      - name: Setup Java
        if: ${{ matrix.target == 'java' }}
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Maven build
        if: ${{ matrix.target == 'java' }}
        run: mvn clean install -DskipTests
