name: 06-security-scan

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sast-and-audit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Node audit
        if: ${{ hashFiles('package-lock.json') != '' || hashFiles('pnpm-lock.yaml') != '' }}
        run: |
          npm install
          npm audit --audit-level=high || true

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@b6643a2595a1cbaad588e40e71356e2b8aea3432 # v0.33.1
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy.sarif

      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@c37a8b7cd97e31de3fcbd9d84c401870edeb8d34 # v3
        with:
          sarif_file: trivy.sarif

      - name: OSV scanner
        uses: google/osv-scanner-action@764c91816374ff2d8fc2095dab36eecd42d61638 # v1.9.2
        with:
          scan-args: "--lockfile=pnpm-lock.yaml --lockfile=poetry.lock"
