# MCP Level 3 - RAG Engine Manifest
# Purpose: Define RAG (Retrieval-Augmented Generation) engine capabilities and configuration
# Version: 1.0.0
# Last Updated: 2025-01-11

manifest:
  # Core Metadata
  name: rag-engine
  version: "1.0.0"
  namespace: mcp.level3.engines.rag
  description: |
    RAG (Retrieval-Augmented Generation) Engine for multi-modal information retrieval.
    Supports vector search, graph traversal, hybrid retrieval, and multimodal RAG.
    Enables context-aware answer generation with provenance tracking.
  
  # Engine Type
  type: retrieval_augmented_generation
  category: knowledge_retrieval
  
  # Capabilities
  capabilities:
    # Vector RAG
    vector_rag:
      enabled: true
      description: Dense vector-based semantic search
      features:
        - embedding_generation
        - similarity_search
        - approximate_nearest_neighbor
        - vector_indexing
        - multi_vector_retrieval
      supported_models:
        - sentence_transformers
        - openai_embeddings
        - cohere_embeddings
        - custom_embeddings
      vector_dimensions:
        - 384
        - 768
        - 1024
        - 1536
      distance_metrics:
        - cosine
        - euclidean
        - dot_product
    
    # Graph RAG
    graph_rag:
      enabled: true
      description: Knowledge graph-based retrieval
      features:
        - entity_linking
        - relationship_traversal
        - subgraph_extraction
        - path_finding
        - community_detection
      supported_graphs:
        - property_graph
        - rdf_graph
        - knowledge_graph
      traversal_algorithms:
        - breadth_first_search
        - depth_first_search
        - shortest_path
        - pagerank
    
    # Hybrid RAG
    hybrid_rag:
      enabled: true
      description: Combined vector and graph retrieval
      features:
        - multi_modal_fusion
        - score_aggregation
        - result_reranking
        - context_merging
      fusion_strategies:
        - weighted_sum
        - reciprocal_rank_fusion
        - learned_fusion
    
    # Multimodal RAG
    multimodal_rag:
      enabled: true
      description: Cross-modal retrieval (text, image, audio)
      features:
        - text_to_image_retrieval
        - image_to_text_retrieval
        - audio_to_text_retrieval
        - cross_modal_embedding
      supported_modalities:
        - text
        - image
        - audio
        - video
    
    # Answer Generation
    answer_generation:
      enabled: true
      description: Context-aware answer synthesis
      features:
        - context_injection
        - citation_generation
        - answer_grounding
        - hallucination_detection
      supported_llms:
        - gpt_4
        - claude
        - llama
        - custom_llm
    
    # Quality & Provenance
    quality_tracking:
      enabled: true
      description: Quality metrics and provenance tracking
      features:
        - relevance_scoring
        - confidence_estimation
        - source_attribution
        - answer_verification
      metrics:
        - precision
        - recall
        - f1_score
        - mrr
        - ndcg
  
  # Interfaces
  interfaces:
    # REST API
    rest_api:
      enabled: true
      base_path: /api/v1/rag
      endpoints:
        - path: /retrieve
          method: POST
          description: Retrieve relevant context
          input_schema: retrieval-request
          output_schema: retrieval-response
        
        - path: /generate
          method: POST
          description: Generate answer from context
          input_schema: generation-request
          output_schema: generated-answer
        
        - path: /query
          method: POST
          description: End-to-end RAG query
          input_schema: rag-query
          output_schema: rag-response
        
        - path: /embed
          method: POST
          description: Generate embeddings
          input_schema: embedding-request
          output_schema: embedding-response
        
        - path: /index
          method: POST
          description: Index documents
          input_schema: indexing-request
          output_schema: indexing-response
    
    # gRPC API
    grpc_api:
      enabled: true
      service: RAGService
      methods:
        - Retrieve
        - Generate
        - Query
        - Embed
        - Index
    
    # Event Streaming
    event_streaming:
      enabled: true
      protocols:
        - kafka
        - rabbitmq
        - redis_streams
      topics:
        - rag.retrieval.requested
        - rag.retrieval.completed
        - rag.generation.requested
        - rag.generation.completed
        - rag.indexing.requested
        - rag.indexing.completed
  
  # Dependencies
  dependencies:
    # Required Services
    required_services:
      - name: vector_database
        type: service
        description: Vector storage and search
        options:
          - pinecone
          - weaviate
          - qdrant
          - milvus
          - pgvector
        min_version: "1.0.0"
      
      - name: graph_database
        type: service
        description: Knowledge graph storage
        options:
          - neo4j
          - neptune
          - tigergraph
        min_version: "4.0.0"
        optional: true
      
      - name: llm_service
        type: service
        description: Language model for generation
        options:
          - openai
          - anthropic
          - local_llm
        min_version: "1.0.0"
    
    # Required Libraries
    required_libraries:
      - name: sentence-transformers
        version: ">=2.2.0"
        purpose: Embedding generation
      
      - name: langchain
        version: ">=0.1.0"
        purpose: RAG orchestration
      
      - name: faiss
        version: ">=1.7.0"
        purpose: Vector similarity search
        optional: true
      
      - name: networkx
        version: ">=3.0"
        purpose: Graph algorithms
        optional: true
    
    # System Requirements
    system_requirements:
      cpu:
        min_cores: 4
        recommended_cores: 8
      memory:
        min_gb: 8
        recommended_gb: 16
      gpu:
        required: false
        recommended: true
        min_vram_gb: 8
      storage:
        min_gb: 50
        recommended_gb: 200
  
  # Configuration
  configuration:
    # Retrieval Settings
    retrieval:
      default_top_k: 10
      max_top_k: 100
      min_similarity_threshold: 0.7
      reranking_enabled: true
      reranking_model: cross-encoder
    
    # Generation Settings
    generation:
      default_max_tokens: 512
      max_max_tokens: 2048
      temperature: 0.7
      top_p: 0.9
      presence_penalty: 0.0
      frequency_penalty: 0.0
    
    # Indexing Settings
    indexing:
      batch_size: 100
      chunk_size: 512
      chunk_overlap: 50
      embedding_batch_size: 32
    
    # Caching
    caching:
      enabled: true
      ttl_seconds: 3600
      max_cache_size_mb: 1024
      cache_backend: redis
    
    # Performance
    performance:
      max_concurrent_requests: 100
      request_timeout_seconds: 30
      embedding_timeout_seconds: 10
      generation_timeout_seconds: 60
  
  # Lifecycle
  lifecycle:
    # Initialization
    initialization:
      steps:
        - name: load_models
          description: Load embedding and generation models
          timeout_seconds: 300
        
        - name: connect_databases
          description: Connect to vector and graph databases
          timeout_seconds: 60
        
        - name: warm_cache
          description: Warm up model cache
          timeout_seconds: 120
          optional: true
    
    # Health Checks
    health_checks:
      liveness:
        endpoint: /health/live
        interval_seconds: 30
        timeout_seconds: 5
        failure_threshold: 3
      
      readiness:
        endpoint: /health/ready
        interval_seconds: 10
        timeout_seconds: 5
        failure_threshold: 3
      
      startup:
        endpoint: /health/startup
        interval_seconds: 10
        timeout_seconds: 5
        failure_threshold: 30
    
    # Graceful Shutdown
    shutdown:
      grace_period_seconds: 30
      steps:
        - name: stop_accepting_requests
          description: Stop accepting new requests
        
        - name: complete_pending_requests
          description: Complete in-flight requests
          timeout_seconds: 30
        
        - name: flush_caches
          description: Flush caches to persistent storage
        
        - name: close_connections
          description: Close database connections
  
  # Monitoring
  monitoring:
    # Metrics
    metrics:
      enabled: true
      export_format: prometheus
      export_port: 9090
      metrics_list:
        # Request Metrics
        - name: rag_requests_total
          type: counter
          description: Total number of RAG requests
          labels:
            - operation
            - status
        
        - name: rag_request_duration_seconds
          type: histogram
          description: RAG request duration
          labels:
            - operation
          buckets: [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
        
        # Retrieval Metrics
        - name: rag_retrieval_results_count
          type: histogram
          description: Number of retrieval results
          buckets: [1, 5, 10, 20, 50, 100]
        
        - name: rag_retrieval_similarity_score
          type: histogram
          description: Retrieval similarity scores
          buckets: [0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 1.0]
        
        # Generation Metrics
        - name: rag_generation_tokens
          type: histogram
          description: Generated token count
          buckets: [50, 100, 200, 500, 1000, 2000]
        
        # Quality Metrics
        - name: rag_answer_quality_score
          type: histogram
          description: Answer quality score
          buckets: [0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 1.0]
    
    # Logging
    logging:
      enabled: true
      level: INFO
      format: json
      outputs:
        - stdout
        - file
      log_file_path: /var/log/rag-engine/rag.log
      log_rotation:
        max_size_mb: 100
        max_files: 10
        compress: true
    
    # Tracing
    tracing:
      enabled: true
      backend: opentelemetry
      sampling_rate: 0.1
      exporters:
        - jaeger
        - zipkin
  
  # Security
  security:
    # Authentication
    authentication:
      enabled: true
      methods:
        - api_key
        - jwt
        - oauth2
      token_validation:
        issuer: auth.example.com
        audience: rag-engine
    
    # Authorization
    authorization:
      enabled: true
      model: rbac
      permissions:
        - rag:retrieve
        - rag:generate
        - rag:query
        - rag:embed
        - rag:index
        - rag:admin
    
    # Rate Limiting
    rate_limiting:
      enabled: true
      default_limit: 100
      window_seconds: 60
      strategy: sliding_window
    
    # Data Security
    data_security:
      encryption_at_rest: true
      encryption_in_transit: true
      pii_detection: true
      data_masking: true
  
  # Artifacts
  artifacts:
    input_artifacts:
      - vector-chunk
      - knowledge-triplet
      - hybrid-context
    
    output_artifacts:
      - generated-answer
      - retrieval-results
      - embedding-vectors
    
    storage_artifacts:
      - indexed-documents
      - vector-embeddings
      - knowledge-graphs
  
  # Integration
  integration:
    # Upstream Services
    upstream:
      - name: data-ingestion
        protocol: rest
        purpose: Document ingestion
      
      - name: preprocessing
        protocol: grpc
        purpose: Text preprocessing
    
    # Downstream Services
    downstream:
      - name: answer-validation
        protocol: rest
        purpose: Answer quality validation
      
      - name: user-interface
        protocol: websocket
        purpose: Real-time answer streaming
    
    # Event Bus
    event_bus:
      enabled: true
      topics_published:
        - rag.answer.generated
        - rag.retrieval.completed
      topics_subscribed:
        - document.indexed
        - model.updated
  
  # Versioning
  versioning:
    api_version: v1
    backward_compatible: true
    deprecation_policy: 6_months
    migration_guide_url: https://docs.example.com/rag-engine/migration
  
  # Documentation
  documentation:
    api_docs_url: https://docs.example.com/rag-engine/api
    user_guide_url: https://docs.example.com/rag-engine/guide
    examples_url: https://docs.example.com/rag-engine/examples
    changelog_url: https://docs.example.com/rag-engine/changelog

# Metadata
metadata:
  created_at: "2025-01-11T00:00:00Z"
  updated_at: "2025-01-11T00:00:00Z"
  maintainers:
    - team:ml-platform
    - team:rag-team
  tags:
    - rag
    - retrieval
    - generation
    - knowledge
  status: active