# MCP Level 3 - RAG Engine Policy
# Defines governance policies, access control, and compliance rules

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EnginePolicy
metadata:
  name: rag-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "RAG Engine Governance and Access Control Policies"
  labels:
    engine-type: rag
    policy-type: governance
    compliance: required
  annotations:
    mcp.ninjatech.ai/policy-version: "1.0.0"
    mcp.ninjatech.ai/enforcement: "strict"

# ============================================================================
# ROLE-BASED ACCESS CONTROL (RBAC)
# ============================================================================

rbac:
  roles:
    # Administrator Role
    - name: rag-admin
      description: "Full administrative access to RAG engine"
      permissions:
        - resource: "*"
          actions: ["*"]
      subjects:
        - kind: User
          names: ["admin@ninjatech.ai"]
        - kind: ServiceAccount
          names: ["rag-admin-sa"]
    
    # Developer Role
    - name: rag-developer
      description: "Development and testing access"
      permissions:
        - resource: "collections"
          actions: ["create", "read", "update", "delete"]
        - resource: "documents"
          actions: ["create", "read", "update", "delete"]
        - resource: "queries"
          actions: ["create", "read"]
        - resource: "indexes"
          actions: ["create", "read", "delete"]
      subjects:
        - kind: Group
          names: ["developers"]
    
    # Data Scientist Role
    - name: rag-data-scientist
      description: "Access for data science and ML operations"
      permissions:
        - resource: "collections"
          actions: ["read"]
        - resource: "documents"
          actions: ["read"]
        - resource: "queries"
          actions: ["create", "read"]
        - resource: "embeddings"
          actions: ["create", "read"]
        - resource: "metrics"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["data-scientists"]
    
    # Application Role
    - name: rag-application
      description: "Runtime access for applications"
      permissions:
        - resource: "queries"
          actions: ["create", "read"]
        - resource: "collections"
          actions: ["read"]
      subjects:
        - kind: ServiceAccount
          names: ["app-*"]
    
    # Read-Only Role
    - name: rag-viewer
      description: "Read-only access for monitoring"
      permissions:
        - resource: "*"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["viewers", "auditors"]

  # Role Bindings
  roleBindings:
    - role: rag-admin
      subjects:
        - kind: User
          name: "admin@ninjatech.ai"
      scope: global
    
    - role: rag-developer
      subjects:
        - kind: Group
          name: "developers"
      scope: namespace
      namespace: "development"
    
    - role: rag-application
      subjects:
        - kind: ServiceAccount
          name: "app-production"
      scope: namespace
      namespace: "production"

# ============================================================================
# AUTHENTICATION & AUTHORIZATION
# ============================================================================

authentication:
  # Authentication Methods
  methods:
    - type: oauth2
      enabled: true
      provider: "auth0"
      config:
        issuer: "https://auth.ninjatech.ai"
        audience: "rag-engine-api"
        scopes:
          - rag:read
          - rag:write
          - rag:admin
    
    - type: api-key
      enabled: true
      header: "X-API-Key"
      validation: "hmac-sha256"
    
    - type: jwt
      enabled: true
      algorithm: "RS256"
      public_key_url: "https://auth.ninjatech.ai/.well-known/jwks.json"
    
    - type: mutual-tls
      enabled: true
      ca_cert: "/etc/certs/ca.crt"
      verify_client: true
  
  # Token Configuration
  tokens:
    access_token:
      lifetime: 3600  # 1 hour
      refresh: true
      refresh_lifetime: 86400  # 24 hours
    
    api_key:
      rotation_period: 90d
      max_keys_per_user: 5

authorization:
  # Authorization Engine
  engine: "opa"  # Open Policy Agent
  
  # Policy Evaluation
  evaluation:
    mode: "strict"
    cache_ttl: 300  # 5 minutes
    deny_by_default: true
  
  # Attribute-Based Access Control (ABAC)
  abac:
    enabled: true
    attributes:
      - name: user.department
        type: string
      - name: user.clearance_level
        type: integer
      - name: resource.sensitivity
        type: string
        values: ["public", "internal", "confidential", "secret"]
      - name: time.business_hours
        type: boolean
    
    rules:
      - name: "confidential-data-access"
        condition: "user.clearance_level >= 3 AND resource.sensitivity == 'confidential'"
        effect: "allow"
      
      - name: "business-hours-only"
        condition: "resource.sensitivity == 'secret' AND time.business_hours == true"
        effect: "allow"

# ============================================================================
# DATA GOVERNANCE
# ============================================================================

data_governance:
  # Data Classification
  classification:
    levels:
      - name: public
        description: "Publicly available data"
        retention: 365d
        encryption: optional
      
      - name: internal
        description: "Internal use only"
        retention: 180d
        encryption: required
      
      - name: confidential
        description: "Confidential business data"
        retention: 90d
        encryption: required
        access_logging: required
      
      - name: secret
        description: "Highly sensitive data"
        retention: 30d
        encryption: required
        access_logging: required
        approval_required: true
  
  # Data Retention
  retention:
    policies:
      - resource: "query_logs"
        period: 90d
        action: "delete"
      
      - resource: "embeddings"
        period: 180d
        action: "archive"
      
      - resource: "generated_answers"
        period: 30d
        action: "anonymize"
  
  # Data Privacy
  privacy:
    pii_detection: true
    pii_masking: true
    pii_fields:
      - email
      - phone
      - ssn
      - credit_card
    
    anonymization:
      enabled: true
      method: "k-anonymity"
      k_value: 5
  
  # Data Quality
  quality:
    validation:
      - rule: "embedding_dimension_check"
        condition: "len(embedding) == 1536"
        severity: "error"
      
      - rule: "content_length_check"
        condition: "len(content) > 0 AND len(content) < 10000"
        severity: "warning"
    
    monitoring:
      - metric: "null_value_rate"
        threshold: 0.05
        action: "alert"

# ============================================================================
# SECURITY POLICIES
# ============================================================================

security:
  # Encryption
  encryption:
    at_rest:
      enabled: true
      algorithm: "AES-256-GCM"
      key_rotation: 90d
    
    in_transit:
      enabled: true
      protocol: "TLS 1.3"
      min_version: "TLS 1.2"
      cipher_suites:
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_CHACHA20_POLY1305_SHA256"
  
  # Rate Limiting
  rate_limiting:
    enabled: true
    rules:
      - scope: "user"
        limit: 1000
        window: "1h"
      
      - scope: "api_key"
        limit: 10000
        window: "1h"
      
      - scope: "ip"
        limit: 100
        window: "1m"
  
  # Input Validation
  input_validation:
    enabled: true
    rules:
      - field: "query"
        max_length: 5000
        sanitize: true
        reject_patterns:
          - "(?i)(drop|delete|truncate)\\s+table"
          - "<script[^>]*>.*?</script>"
      
      - field: "collection"
        pattern: "^[a-zA-Z0-9_-]+$"
        max_length: 100
  
  # Threat Protection
  threat_protection:
    sql_injection: true
    xss_protection: true
    csrf_protection: true
    
    waf:
      enabled: true
      rules:
        - "OWASP Core Rule Set"
        - "Custom RAG Rules"

# ============================================================================
# COMPLIANCE POLICIES
# ============================================================================

compliance:
  # Regulatory Frameworks
  frameworks:
    - name: "GDPR"
      enabled: true
      requirements:
        - right_to_access
        - right_to_erasure
        - data_portability
        - consent_management
    
    - name: "SOC2"
      enabled: true
      controls:
        - access_control
        - encryption
        - monitoring
        - incident_response
    
    - name: "HIPAA"
      enabled: false
  
  # Audit Requirements
  audit:
    enabled: true
    events:
      - "authentication"
      - "authorization"
      - "data_access"
      - "data_modification"
      - "policy_change"
      - "configuration_change"
    
    retention: 365d
    immutable: true
    
    log_format:
      timestamp: true
      user_id: true
      action: true
      resource: true
      result: true
      ip_address: true
      user_agent: true
  
  # Compliance Monitoring
  monitoring:
    - metric: "unauthorized_access_attempts"
      threshold: 10
      window: "1h"
      action: "alert"
    
    - metric: "policy_violations"
      threshold: 5
      window: "1d"
      action: "alert"

# ============================================================================
# OPERATIONAL POLICIES
# ============================================================================

operational:
  # Resource Quotas
  quotas:
    - scope: "user"
      limits:
        collections: 10
        documents_per_collection: 100000
        queries_per_day: 1000
    
    - scope: "team"
      limits:
        collections: 100
        documents_per_collection: 1000000
        queries_per_day: 100000
  
  # Cost Management
  cost_management:
    budgets:
      - scope: "project"
        monthly_limit: 10000
        currency: "USD"
        alerts:
          - threshold: 0.8
            action: "notify"
          - threshold: 1.0
            action: "throttle"
  
  # Performance Policies
  performance:
    - metric: "query_latency_p95"
      threshold: 500
      unit: "ms"
      action: "scale_up"
    
    - metric: "error_rate"
      threshold: 0.01
      window: "5m"
      action: "alert"

# ============================================================================
# POLICY ENFORCEMENT
# ============================================================================

enforcement:
  # Enforcement Mode
  mode: "strict"  # strict, permissive, audit-only
  
  # Violation Handling
  violations:
    - severity: "critical"
      action: "block"
      notify: ["security-team@ninjatech.ai"]
    
    - severity: "high"
      action: "block"
      notify: ["ops-team@ninjatech.ai"]
    
    - severity: "medium"
      action: "warn"
      notify: ["dev-team@ninjatech.ai"]
    
    - severity: "low"
      action: "log"
  
  # Policy Updates
  updates:
    approval_required: true
    approvers:
      - "security-lead"
      - "compliance-officer"
    
    rollback:
      enabled: true
      retention: 5

# ============================================================================
# DOCUMENTATION
# ============================================================================

documentation:
  policy_guide: "https://docs.ninjatech.ai/mcp/rag-engine/policies"
  compliance_guide: "https://docs.ninjatech.ai/mcp/compliance"
  security_guide: "https://docs.ninjatech.ai/mcp/security"