# MCP Level 3 - RAG Engine Specification
# Defines API specifications, interface contracts, and integration patterns

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineSpec
metadata:
  name: rag-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Retrieval-Augmented Generation Engine API Specification"
  labels:
    engine-type: rag
    capability: retrieval-generation
    tier: core
  annotations:
    mcp.ninjatech.ai/spec-version: "1.0.0"
    mcp.ninjatech.ai/last-updated: "2024-01-15"

# ============================================================================
# API SPECIFICATIONS
# ============================================================================

api:
  # REST API Specification
  rest:
    baseUrl: "/api/v1/rag"
    version: "1.0.0"
    
    endpoints:
      # Vector Retrieval Endpoints
      - path: "/retrieve/vector"
        method: POST
        operationId: retrieveVector
        summary: "Retrieve documents using vector similarity search"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [query, collection]
                properties:
                  query:
                    type: string
                    description: "Query text to embed and search"
                  collection:
                    type: string
                    description: "Vector collection name"
                  top_k:
                    type: integer
                    default: 10
                    minimum: 1
                    maximum: 100
                  filters:
                    type: object
                    description: "Metadata filters"
                  embedding_model:
                    type: string
                    default: "text-embedding-ada-002"
        responses:
          200:
            description: "Successful retrieval"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/VectorRetrievalResponse"
          400:
            $ref: "#/components/responses/BadRequest"
          500:
            $ref: "#/components/responses/InternalError"
      
      # Graph Retrieval Endpoints
      - path: "/retrieve/graph"
        method: POST
        operationId: retrieveGraph
        summary: "Retrieve knowledge using graph traversal"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [query, graph_name]
                properties:
                  query:
                    type: string
                  graph_name:
                    type: string
                  max_depth:
                    type: integer
                    default: 3
                  relationship_types:
                    type: array
                    items:
                      type: string
        responses:
          200:
            description: "Successful graph retrieval"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/GraphRetrievalResponse"
      
      # Hybrid Retrieval Endpoints
      - path: "/retrieve/hybrid"
        method: POST
        operationId: retrieveHybrid
        summary: "Retrieve using hybrid vector + graph approach"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [query]
                properties:
                  query:
                    type: string
                  vector_weight:
                    type: number
                    default: 0.7
                    minimum: 0
                    maximum: 1
                  graph_weight:
                    type: number
                    default: 0.3
                  fusion_strategy:
                    type: string
                    enum: [rrf, weighted_sum, cascade]
                    default: rrf
        responses:
          200:
            description: "Successful hybrid retrieval"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/HybridRetrievalResponse"
      
      # Answer Generation Endpoints
      - path: "/generate/answer"
        method: POST
        operationId: generateAnswer
        summary: "Generate answer using retrieved context"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [query, context]
                properties:
                  query:
                    type: string
                  context:
                    type: array
                    items:
                      type: object
                  llm_model:
                    type: string
                    default: "gpt-4"
                  temperature:
                    type: number
                    default: 0.7
                  max_tokens:
                    type: integer
                    default: 500
                  system_prompt:
                    type: string
        responses:
          200:
            description: "Generated answer"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/AnswerResponse"
      
      # End-to-End RAG Pipeline
      - path: "/rag/query"
        method: POST
        operationId: ragQuery
        summary: "Execute complete RAG pipeline"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [query]
                properties:
                  query:
                    type: string
                  retrieval_strategy:
                    type: string
                    enum: [vector, graph, hybrid]
                    default: hybrid
                  generation_config:
                    type: object
                  retrieval_config:
                    type: object
        responses:
          200:
            description: "RAG pipeline result"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/RAGResponse"
      
      # Indexing Endpoints
      - path: "/index/documents"
        method: POST
        operationId: indexDocuments
        summary: "Index documents for retrieval"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [documents, collection]
                properties:
                  documents:
                    type: array
                    items:
                      type: object
                  collection:
                    type: string
                  chunking_strategy:
                    type: string
                    enum: [fixed, semantic, recursive]
                  chunk_size:
                    type: integer
                  chunk_overlap:
                    type: integer
        responses:
          201:
            description: "Documents indexed successfully"
      
      # Collection Management
      - path: "/collections"
        method: GET
        operationId: listCollections
        summary: "List available collections"
        responses:
          200:
            description: "List of collections"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/Collection"
      
      - path: "/collections/{collection_id}"
        method: DELETE
        operationId: deleteCollection
        summary: "Delete a collection"
        parameters:
          - name: collection_id
            in: path
            required: true
            schema:
              type: string
        responses:
          204:
            description: "Collection deleted"
  
  # gRPC API Specification
  grpc:
    package: "mcp.rag.v1"
    services:
      - name: RAGService
        methods:
          - name: RetrieveVector
            input: VectorRetrievalRequest
            output: VectorRetrievalResponse
            streaming: false
          
          - name: RetrieveGraph
            input: GraphRetrievalRequest
            output: GraphRetrievalResponse
            streaming: false
          
          - name: GenerateAnswer
            input: AnswerGenerationRequest
            output: AnswerGenerationResponse
            streaming: true
          
          - name: RAGQuery
            input: RAGQueryRequest
            output: RAGQueryResponse
            streaming: true
          
          - name: IndexDocuments
            input: stream DocumentIndexRequest
            output: IndexingResponse
            streaming: true
  
  # Event Streaming Specification
  events:
    protocol: kafka
    topics:
      - name: rag.retrieval.requested
        schema: RetrievalRequestedEvent
        partitions: 10
        retention: 7d
      
      - name: rag.retrieval.completed
        schema: RetrievalCompletedEvent
        partitions: 10
        retention: 7d
      
      - name: rag.generation.started
        schema: GenerationStartedEvent
        partitions: 5
        retention: 3d
      
      - name: rag.generation.completed
        schema: GenerationCompletedEvent
        partitions: 5
        retention: 7d
      
      - name: rag.indexing.completed
        schema: IndexingCompletedEvent
        partitions: 5
        retention: 30d

# ============================================================================
# DATA SCHEMAS
# ============================================================================

components:
  schemas:
    VectorRetrievalResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              chunk_id:
                type: string
              content:
                type: string
              score:
                type: number
              metadata:
                type: object
        query_embedding:
          type: array
          items:
            type: number
        total_results:
          type: integer
        execution_time_ms:
          type: number
    
    GraphRetrievalResponse:
      type: object
      properties:
        triplets:
          type: array
          items:
            type: object
            properties:
              subject:
                type: string
              predicate:
                type: string
              object:
                type: string
              confidence:
                type: number
        paths:
          type: array
          items:
            type: array
            items:
              type: string
        execution_time_ms:
          type: number
    
    HybridRetrievalResponse:
      type: object
      properties:
        vector_results:
          type: array
        graph_results:
          type: array
        fused_results:
          type: array
        fusion_scores:
          type: object
        execution_time_ms:
          type: number
    
    AnswerResponse:
      type: object
      properties:
        answer:
          type: string
        sources:
          type: array
          items:
            type: object
        confidence:
          type: number
        tokens_used:
          type: integer
        generation_time_ms:
          type: number
    
    RAGResponse:
      type: object
      properties:
        query:
          type: string
        answer:
          type: string
        retrieved_context:
          type: array
        sources:
          type: array
        metrics:
          type: object
          properties:
            retrieval_time_ms:
              type: number
            generation_time_ms:
              type: number
            total_time_ms:
              type: number
            tokens_used:
              type: integer
    
    Collection:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        document_count:
          type: integer
        embedding_model:
          type: string
        created_at:
          type: string
          format: date-time
  
  responses:
    BadRequest:
      description: "Invalid request parameters"
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: object
    
    InternalError:
      description: "Internal server error"
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              trace_id:
                type: string

# ============================================================================
# INTERFACE CONTRACTS
# ============================================================================

contracts:
  # Service Level Agreements
  sla:
    availability: 99.9%
    latency:
      p50: 200ms
      p95: 500ms
      p99: 1000ms
    throughput:
      requests_per_second: 1000
      concurrent_requests: 100
  
  # Quality Guarantees
  quality:
    retrieval:
      min_relevance_score: 0.7
      max_results: 100
      timeout: 5s
    
    generation:
      min_coherence_score: 0.8
      max_tokens: 2000
      timeout: 30s
  
  # Data Contracts
  data:
    input:
      - format: text/plain
        max_size: 10MB
      - format: application/json
        max_size: 5MB
    
    output:
      - format: application/json
        encoding: utf-8

# ============================================================================
# INTEGRATION PATTERNS
# ============================================================================

integration:
  # Upstream Dependencies
  upstream:
    - service: vector-database
      protocol: grpc
      endpoints:
        - search
        - insert
        - delete
    
    - service: graph-database
      protocol: bolt
      endpoints:
        - query
        - traverse
    
    - service: llm-service
      protocol: rest
      endpoints:
        - /v1/completions
        - /v1/embeddings
  
  # Downstream Consumers
  downstream:
    - service: application-layer
      protocol: rest
      patterns:
        - request-response
        - streaming
    
    - service: analytics-service
      protocol: kafka
      topics:
        - rag.metrics
        - rag.usage
  
  # Event Bus Integration
  event_bus:
    producer:
      - rag.retrieval.completed
      - rag.generation.completed
      - rag.indexing.completed
    
    consumer:
      - document.uploaded
      - collection.updated
      - model.updated

# ============================================================================
# VERSIONING & COMPATIBILITY
# ============================================================================

versioning:
  strategy: semantic
  current: 1.0.0
  supported:
    - 1.0.0
  deprecated: []
  
  compatibility:
    backward: true
    forward: false
  
  migration:
    from: []
    to: []

# ============================================================================
# DOCUMENTATION
# ============================================================================

documentation:
  openapi: "https://docs.ninjatech.ai/mcp/rag-engine/openapi.yaml"
  swagger_ui: "https://api.ninjatech.ai/rag/docs"
  postman: "https://www.postman.com/ninjatech/rag-engine"
  examples: "https://github.com/ninjatech/mcp-examples/rag"