# MCP Level 3 - Artifact Registry Policy
# Defines governance policies, access control, and compliance rules

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EnginePolicy
metadata:
  name: artifact-registry
  namespace: mcp-level3
  version: 1.0.0
  description: "Artifact Registry Governance and Access Control Policies"
  labels:
    engine-type: artifact-registry
    policy-type: governance
    compliance: required
  annotations:
    mcp.ninjatech.ai/policy-version: "1.0.0"
    mcp.ninjatech.ai/enforcement: "strict"

# ============================================================================
# ROLE-BASED ACCESS CONTROL (RBAC)
# ============================================================================

rbac:
  roles:
    - name: registry-admin
      description: "Full administrative access"
      permissions:
        - resource: "*"
          actions: ["*"]
      subjects:
        - kind: User
          names: ["admin@ninjatech.ai"]
    
    - name: artifact-publisher
      description: "Upload and manage artifacts"
      permissions:
        - resource: "artifacts"
          actions: ["create", "read", "update", "delete"]
        - resource: "metadata"
          actions: ["create", "read", "update"]
        - resource: "tags"
          actions: ["create", "delete"]
      subjects:
        - kind: Group
          names: ["publishers", "ci-cd-systems"]
        - kind: ServiceAccount
          names: ["publisher-sa"]
    
    - name: artifact-consumer
      description: "Download and read artifacts"
      permissions:
        - resource: "artifacts"
          actions: ["read", "download"]
        - resource: "metadata"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["consumers", "developers"]
    
    - name: registry-viewer
      description: "Read-only access"
      permissions:
        - resource: "*"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["viewers"]

authentication:
  methods:
    - type: oauth2
      enabled: true
      provider: "auth0"
      config:
        issuer: "https://auth.ninjatech.ai"
        audience: "artifact-registry-api"
    
    - type: api-key
      enabled: true
      header: "X-API-Key"
    
    - type: docker-registry-token
      enabled: true
      for_types: ["container-image"]

authorization:
  engine: "opa"
  evaluation:
    mode: "strict"
    deny_by_default: true

# ============================================================================
# ARTIFACT GOVERNANCE
# ============================================================================

artifact_governance:
  # Artifact Validation
  validation:
    - rule: "artifact_size_limit"
      condition: "artifact.size <= 10GB"
      severity: "error"
      message: "Artifact size cannot exceed 10GB"
    
    - rule: "artifact_naming_convention"
      condition: "matches(artifact.name, '^[a-z0-9-]+$')"
      severity: "warning"
      message: "Artifact name should use lowercase alphanumeric and hyphens"
    
    - rule: "version_format"
      condition: "matches(artifact.version, '^v?[0-9]+\\.[0-9]+\\.[0-9]+$')"
      severity: "error"
      message: "Version must follow semantic versioning"
    
    - rule: "required_metadata"
      condition: "has_all(artifact.metadata, ['author', 'description', 'license'])"
      severity: "warning"
      message: "Artifact should include author, description, and license metadata"
  
  # Artifact Lifecycle
  lifecycle:
    retention:
      - type: "snapshot"
        period: 7d
      
      - type: "release"
        period: 365d
      
      - type: "production"
        period: 2555d  # 7 years
    
    immutability:
      enabled: true
      exceptions:
        - "snapshot versions"
        - "development artifacts"
  
  # Version Management
  versioning:
    strategy: "semantic"
    
    policies:
      - rule: "no_version_overwrite"
        condition: "not exists(artifact.version)"
        enforcement: "strict"
      
      - rule: "sequential_versions"
        condition: "new_version > latest_version"
        enforcement: "warning"

# ============================================================================
# SECURITY POLICIES
# ============================================================================

security:
  # Encryption
  encryption:
    at_rest:
      enabled: true
      algorithm: "AES-256-GCM"
      key_rotation: 90d
    
    in_transit:
      enabled: true
      protocol: "TLS 1.3"
  
  # Artifact Verification
  verification:
    checksum:
      enabled: true
      algorithm: "SHA-256"
      required: true
    
    signature:
      enabled: true
      required_for:
        - "production artifacts"
        - "release artifacts"
      algorithms:
        - "RSA-4096"
        - "ECDSA-P256"
    
    vulnerability_scanning:
      enabled: true
      on_upload: true
      periodic: true
      frequency: "daily"
      
      severity_thresholds:
        critical: 0
        high: 5
        medium: 20
  
  # Access Control
  access_control:
    download_limits:
      - scope: "user"
        limit: 1000
        window: "1h"
      
      - scope: "ip"
        limit: 10000
        window: "1h"
    
    upload_limits:
      - scope: "user"
        limit: 100
        window: "1h"
      
      - scope: "service_account"
        limit: 1000
        window: "1h"

# ============================================================================
# DATA GOVERNANCE
# ============================================================================

data_governance:
  # Metadata Management
  metadata:
    required_fields:
      - name
      - version
      - type
      - author
      - created_at
    
    custom_fields:
      allowed: true
      max_count: 50
      max_size: "10KB"
  
  # Lineage Tracking
  lineage:
    enabled: true
    capture:
      - source_artifacts
      - build_process
      - dependencies
      - transformations
    
    retention: 365d
  
  # Storage Management
  storage:
    quotas:
      - scope: "user"
        limit: "100GB"
      
      - scope: "team"
        limit: "1TB"
      
      - scope: "organization"
        limit: "10TB"
    
    cleanup:
      enabled: true
      rules:
        - condition: "artifact.type == 'snapshot' AND age > 7d"
          action: "delete"
        
        - condition: "artifact.downloads == 0 AND age > 90d"
          action: "archive"

# ============================================================================
# COMPLIANCE POLICIES
# ============================================================================

compliance:
  frameworks:
    - name: "SOC2"
      enabled: true
      controls:
        - access_control
        - encryption
        - audit_logging
        - version_control
    
    - name: "GDPR"
      enabled: true
      requirements:
        - data_minimization
        - storage_limitation
  
  audit:
    enabled: true
    events:
      - "artifact_uploaded"
      - "artifact_downloaded"
      - "artifact_deleted"
      - "metadata_updated"
      - "access_denied"
      - "vulnerability_detected"
    
    retention: 365d
    immutable: true
  
  licensing:
    tracking: true
    allowed_licenses:
      - "MIT"
      - "Apache-2.0"
      - "BSD-3-Clause"
      - "GPL-3.0"
    
    prohibited_licenses:
      - "AGPL-3.0"
    
    require_license_declaration: true

# ============================================================================
# OPERATIONAL POLICIES
# ============================================================================

operational:
  # High Availability
  replication:
    enabled: true
    factor: 3
    regions:
      - "us-east-1"
      - "us-west-2"
      - "eu-west-1"
  
  # Backup
  backup:
    enabled: true
    frequency: "daily"
    retention: 30d
    
    verification:
      enabled: true
      frequency: "weekly"
  
  # Performance
  performance:
    - metric: "upload_latency_p95"
      threshold: 1000
      unit: "ms"
      action: "alert"
    
    - metric: "download_latency_p95"
      threshold: 500
      unit: "ms"
      action: "alert"
    
    - metric: "storage_usage"
      threshold: 0.85
      action: "alert"

# ============================================================================
# POLICY ENFORCEMENT
# ============================================================================

enforcement:
  mode: "strict"
  
  violations:
    - severity: "critical"
      action: "block"
      notify: ["security-team@ninjatech.ai", "registry-admin@ninjatech.ai"]
    
    - severity: "high"
      action: "block"
      notify: ["ops-team@ninjatech.ai"]
    
    - severity: "medium"
      action: "warn"
      notify: ["dev-team@ninjatech.ai"]
    
    - severity: "low"
      action: "log"
  
  updates:
    approval_required: true
    approvers: ["registry-admin", "security-lead"]
    
    rollback:
      enabled: true
      retention: 5

# ============================================================================
# DOCUMENTATION
# ============================================================================

documentation:
  policy_guide: "https://docs.ninjatech.ai/mcp/artifact-registry/policies"
  security_guide: "https://docs.ninjatech.ai/mcp/artifact-security"
  compliance_guide: "https://docs.ninjatech.ai/mcp/compliance"