# MCP Level 3 - Artifact Registry Specification
# Defines API specifications, interface contracts, and integration patterns

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineSpec
metadata:
  name: artifact-registry
  namespace: mcp-level3
  version: 1.0.0
  description: "Artifact Registry API Specification"
  labels:
    engine-type: artifact-registry
    capability: artifact-management
    tier: core
  annotations:
    mcp.ninjatech.ai/spec-version: "1.0.0"
    mcp.ninjatech.ai/last-updated: "2024-01-15"

# ============================================================================
# API SPECIFICATIONS
# ============================================================================

api:
  rest:
    baseUrl: "/api/v1/registry"
    version: "1.0.0"
    
    endpoints:
      # Artifact Management
      - path: "/artifacts"
        method: POST
        operationId: uploadArtifact
        summary: "Upload a new artifact"
        requestBody:
          required: true
          content:
            multipart/form-data:
              schema:
                type: object
                required: [file, metadata]
                properties:
                  file:
                    type: string
                    format: binary
                  metadata:
                    type: object
                    properties:
                      name:
                        type: string
                      version:
                        type: string
                      type:
                        type: string
                      tags:
                        type: array
                        items:
                          type: string
        responses:
          201:
            description: "Artifact uploaded"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ArtifactResponse"
      
      - path: "/artifacts"
        method: GET
        operationId: listArtifacts
        summary: "List all artifacts"
        parameters:
          - name: type
            in: query
            schema:
              type: string
          - name: tags
            in: query
            schema:
              type: array
              items:
                type: string
          - name: version
            in: query
            schema:
              type: string
        responses:
          200:
            description: "List of artifacts"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/ArtifactSummary"
      
      - path: "/artifacts/{artifact_id}"
        method: GET
        operationId: getArtifact
        summary: "Get artifact details"
        parameters:
          - name: artifact_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Artifact details"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ArtifactResponse"
      
      - path: "/artifacts/{artifact_id}/download"
        method: GET
        operationId: downloadArtifact
        summary: "Download an artifact"
        parameters:
          - name: artifact_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Artifact file"
            content:
              application/octet-stream:
                schema:
                  type: string
                  format: binary
      
      - path: "/artifacts/{artifact_id}"
        method: DELETE
        operationId: deleteArtifact
        summary: "Delete an artifact"
        parameters:
          - name: artifact_id
            in: path
            required: true
            schema:
              type: string
        responses:
          204:
            description: "Artifact deleted"
      
      # Version Management
      - path: "/artifacts/{artifact_id}/versions"
        method: GET
        operationId: listVersions
        summary: "List artifact versions"
        parameters:
          - name: artifact_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "List of versions"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/VersionInfo"
      
      - path: "/artifacts/{artifact_id}/versions/{version}"
        method: GET
        operationId: getVersion
        summary: "Get specific version"
        parameters:
          - name: artifact_id
            in: path
            required: true
            schema:
              type: string
          - name: version
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Version details"
      
      # Metadata Management
      - path: "/artifacts/{artifact_id}/metadata"
        method: PUT
        operationId: updateMetadata
        summary: "Update artifact metadata"
        parameters:
          - name: artifact_id
            in: path
            required: true
            schema:
              type: string
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
        responses:
          200:
            description: "Metadata updated"
      
      - path: "/artifacts/{artifact_id}/metadata"
        method: GET
        operationId: getMetadata
        summary: "Get artifact metadata"
        parameters:
          - name: artifact_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Artifact metadata"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Metadata"
      
      # Lineage Tracking
      - path: "/artifacts/{artifact_id}/lineage"
        method: GET
        operationId: getArtifactLineage
        summary: "Get artifact lineage"
        parameters:
          - name: artifact_id
            in: path
            required: true
            schema:
              type: string
          - name: direction
            in: query
            schema:
              type: string
              enum: [upstream, downstream, both]
        responses:
          200:
            description: "Artifact lineage"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/LineageGraph"
      
      # Search
      - path: "/artifacts/search"
        method: POST
        operationId: searchArtifacts
        summary: "Search for artifacts"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                  filters:
                    type: object
                  sort:
                    type: object
                  limit:
                    type: integer
        responses:
          200:
            description: "Search results"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/ArtifactSummary"
      
      # Tags Management
      - path: "/artifacts/{artifact_id}/tags"
        method: POST
        operationId: addTags
        summary: "Add tags to artifact"
        parameters:
          - name: artifact_id
            in: path
            required: true
            schema:
              type: string
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [tags]
                properties:
                  tags:
                    type: array
                    items:
                      type: string
        responses:
          200:
            description: "Tags added"
      
      - path: "/artifacts/{artifact_id}/tags/{tag}"
        method: DELETE
        operationId: removeTag
        summary: "Remove tag from artifact"
        parameters:
          - name: artifact_id
            in: path
            required: true
            schema:
              type: string
          - name: tag
            in: path
            required: true
            schema:
              type: string
        responses:
          204:
            description: "Tag removed"
      
      # Storage Management
      - path: "/storage/usage"
        method: GET
        operationId: getStorageUsage
        summary: "Get storage usage statistics"
        responses:
          200:
            description: "Storage usage"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/StorageUsage"
  
  grpc:
    package: "mcp.registry.v1"
    services:
      - name: ArtifactRegistryService
        methods:
          - name: UploadArtifact
            input: stream UploadArtifactRequest
            output: ArtifactResponse
            streaming: true
          
          - name: DownloadArtifact
            input: DownloadArtifactRequest
            output: stream ArtifactChunk
            streaming: true
          
          - name: GetArtifact
            input: GetArtifactRequest
            output: ArtifactResponse
          
          - name: SearchArtifacts
            input: SearchRequest
            output: SearchResponse
  
  events:
    protocol: kafka
    topics:
      - name: registry.artifact.uploaded
        schema: ArtifactUploadedEvent
        partitions: 10
        retention: 30d
      
      - name: registry.artifact.downloaded
        schema: ArtifactDownloadedEvent
        partitions: 10
        retention: 7d
      
      - name: registry.artifact.deleted
        schema: ArtifactDeletedEvent
        partitions: 5
        retention: 90d
      
      - name: registry.metadata.updated
        schema: MetadataUpdatedEvent
        partitions: 5
        retention: 30d

# ============================================================================
# DATA SCHEMAS
# ============================================================================

components:
  schemas:
    ArtifactResponse:
      type: object
      properties:
        artifact_id:
          type: string
        name:
          type: string
        version:
          type: string
        type:
          type: string
        size:
          type: integer
        checksum:
          type: string
        storage_path:
          type: string
        created_at:
          type: string
          format: date-time
        metadata:
          type: object
    
    ArtifactSummary:
      type: object
      properties:
        artifact_id:
          type: string
        name:
          type: string
        version:
          type: string
        type:
          type: string
        tags:
          type: array
          items:
            type: string
    
    VersionInfo:
      type: object
      properties:
        version:
          type: string
        created_at:
          type: string
          format: date-time
        size:
          type: integer
        checksum:
          type: string
    
    Metadata:
      type: object
      properties:
        artifact_id:
          type: string
        custom_fields:
          type: object
        tags:
          type: array
        lineage:
          type: object
    
    LineageGraph:
      type: object
      properties:
        artifact_id:
          type: string
        upstream:
          type: array
        downstream:
          type: array
        relationships:
          type: array
    
    StorageUsage:
      type: object
      properties:
        total_size:
          type: integer
        artifact_count:
          type: integer
        by_type:
          type: object

contracts:
  sla:
    availability: 99.99%
    latency:
      p50: 100ms
      p95: 300ms
      p99: 500ms
    throughput:
      uploads_per_second: 100
      downloads_per_second: 1000

integration:
  upstream:
    - service: object-storage
      protocol: s3
    - service: metadata-database
      protocol: postgresql
  
  downstream:
    - service: search-engine
      protocol: elasticsearch
    - service: cdn
      protocol: https

versioning:
  strategy: semantic
  current: 1.0.0
  supported: [1.0.0]

documentation:
  openapi: "https://docs.ninjatech.ai/mcp/artifact-registry/openapi.yaml"