# MCP Level 3 - Artifact Registry Dependency Graph

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineGraph
metadata:
  name: artifact-registry
  namespace: mcp-level3
  version: 1.0.0
  description: "Artifact Registry dependency graph"
  labels:
    engine-type: artifact-registry
    graph-type: dependency

nodes:
  - id: registry-api-service
    type: service
    category: api
    name: "Registry API Service"
    properties:
      port: 8080
      replicas: 5
      criticality: critical
  
  - id: artifact-storage-service
    type: service
    category: core
    name: "Artifact Storage Service"
    properties:
      port: 8081
      replicas: 10
      criticality: critical
  
  - id: metadata-service
    type: service
    category: core
    name: "Metadata Service"
    properties:
      port: 8082
      replicas: 5
      criticality: critical
  
  - id: version-service
    type: service
    category: core
    name: "Version Service"
    properties:
      port: 8083
      replicas: 3
      criticality: high
  
  - id: lineage-service
    type: service
    category: tracking
    name: "Lineage Service"
    properties:
      port: 8084
      replicas: 3
      criticality: medium
  
  - id: scan-service
    type: service
    category: security
    name: "Scan Service"
    properties:
      port: 8085
      replicas: 3
      criticality: high
  
  - id: object-storage
    type: datastore
    category: storage
    name: "Object Storage"
    properties:
      provider: s3
      criticality: critical
  
  - id: metadata-database
    type: datastore
    category: storage
    name: "Metadata Database"
    properties:
      provider: postgresql
      criticality: critical
  
  - id: search-engine
    type: datastore
    category: storage
    name: "Search Engine"
    properties:
      provider: elasticsearch
      criticality: high
  
  - id: cache-layer
    type: datastore
    category: cache
    name: "Cache Layer"
    properties:
      provider: redis
      criticality: high

edges:
  - source: registry-api-service
    target: artifact-storage-service
    type: synchronous
    protocol: grpc
    properties:
      latency: 50ms
      throughput: 1000rps
  
  - source: registry-api-service
    target: metadata-service
    type: synchronous
    protocol: grpc
    properties:
      latency: 30ms
      throughput: 2000rps
  
  - source: artifact-storage-service
    target: object-storage
    type: synchronous
    protocol: s3
    properties:
      latency: 100ms
      throughput: 500rps
  
  - source: artifact-storage-service
    target: cache-layer
    type: synchronous
    protocol: redis
    properties:
      latency: 5ms
      throughput: 5000rps
  
  - source: metadata-service
    target: metadata-database
    type: synchronous
    protocol: postgresql
    properties:
      latency: 20ms
      throughput: 5000rps
  
  - source: metadata-service
    target: search-engine
    type: asynchronous
    protocol: http
    properties:
      latency: 50ms
  
  - source: version-service
    target: metadata-database
    type: synchronous
    protocol: postgresql
    properties:
      latency: 20ms
      throughput: 2000rps
  
  - source: lineage-service
    target: metadata-database
    type: synchronous
    protocol: postgresql
    properties:
      latency: 30ms
      throughput: 1000rps
  
  - source: scan-service
    target: object-storage
    type: synchronous
    protocol: s3
    properties:
      latency: 200ms
      throughput: 100rps
  
  - source: scan-service
    target: metadata-database
    type: synchronous
    protocol: postgresql
    properties:
      latency: 20ms
      throughput: 500rps

dependency_matrix:
  services:
    - registry-api-service
    - artifact-storage-service
    - metadata-service
    - version-service
    - lineage-service
    - scan-service
  
  matrix:
    registry-api-service: [0, 1, 1, 0, 0, 0]
    artifact-storage-service: [0, 0, 0, 0, 0, 0]
    metadata-service: [0, 0, 0, 0, 0, 0]
    version-service: [0, 0, 1, 0, 0, 0]
    lineage-service: [0, 0, 1, 0, 0, 0]
    scan-service: [0, 1, 1, 0, 0, 0]

data_flows:
  - name: upload-flow
    description: "Artifact upload flow"
    steps:
      - step: 1
        component: registry-api-service
        action: "Receive upload request"
      - step: 2
        component: artifact-storage-service
        action: "Store artifact"
      - step: 3
        component: metadata-service
        action: "Store metadata"
      - step: 4
        component: scan-service
        action: "Scan for vulnerabilities"
  
  - name: download-flow
    description: "Artifact download flow"
    steps:
      - step: 1
        component: registry-api-service
        action: "Receive download request"
      - step: 2
        component: cache-layer
        action: "Check cache"
      - step: 3
        component: artifact-storage-service
        action: "Retrieve artifact"

critical_paths:
  - name: upload-critical-path
    path:
      - registry-api-service
      - artifact-storage-service
      - object-storage
    total_latency: 150ms
    bottlenecks:
      - component: object-storage
        latency: 100ms
        percentage: 66.7
  
  - name: download-critical-path
    path:
      - registry-api-service
      - artifact-storage-service
      - cache-layer
    total_latency: 55ms

integration_points:
  upstream:
    - name: api-gateway
      type: ingress
      protocol: https
      endpoints:
        - "/api/v1/registry/*"
  
  downstream:
    - name: object-storage
      type: storage
      protocol: s3
      endpoints:
        - "s3.amazonaws.com"
    
    - name: cdn
      type: cdn
      protocol: https
      endpoints:
        - "cdn.ninjatech.ai"

failure_modes:
  - component: object-storage
    failure: "S3 unavailable"
    impact: "Critical - Cannot upload/download artifacts"
    mitigation:
      - "Use cache for downloads"
      - "Queue uploads for retry"
      - "Failover to secondary region"
    recovery_time: "5 minutes"
  
  - component: metadata-database
    failure: "Database unavailable"
    impact: "High - Cannot query metadata"
    mitigation:
      - "Use read replicas"
      - "Cache metadata"
    recovery_time: "2 minutes"

performance:
  throughput:
    uploads_per_second: 100
    downloads_per_second: 1000
  
  latency:
    upload_p50: 150ms
    upload_p95: 500ms
    upload_p99: 1000ms
    download_p50: 50ms
    download_p95: 200ms
    download_p99: 500ms

documentation:
  architecture_diagram: "https://docs.ninjatech.ai/mcp/artifact-registry/architecture"
  data_flow_diagram: "https://docs.ninjatech.ai/mcp/artifact-registry/data-flow"
