---
name: 📚 Documentation Improvement
description: Suggest improvements to our documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please fill out the form below.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this about?
      options:
        - README
        - API Reference
        - Tutorial/Guide
        - Code Comments
        - Architecture Docs
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: input
    id: doc-url
    attributes:
      label: Documentation URL
      description: Link to the documentation page (if applicable)
      placeholder: https://docs.machinenativeops.io/...

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of improvement is needed?
      options:
        - Missing Information
        - Incorrect Information
        - Unclear/Confusing
        - Outdated
        - Typo/Grammar
        - Code Example Needed
        - Translation Needed
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the documentation issue or improvement.
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you like to see this improved?

  - type: checkboxes
    id: contribution
    attributes:
      label: Are you willing to contribute?
      description: Would you be interested in making this improvement?
      options:
        - label: I would like to update this documentation
