---
name: ✨ Feature Request
description: Suggest a new feature for SynergyMesh
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please fill out the form below.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a feature request already exists.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does this feature fall under?
      options:
        - Cloud-Native Platform
        - AI-Powered Automation
        - Seamless Integration
        - Real-Time Analytics
        - Enterprise Security
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Cannot use without it
        - High - Important for my use case
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases that would benefit from this feature.
      placeholder: |
        1. As a developer, I want to...
        2. As an enterprise user, I need to...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here.

  - type: checkboxes
    id: contribution
    attributes:
      label: Are you willing to contribute?
      description: Would you be interested in implementing this feature?
      options:
        - label: I would like to implement this feature
        - label: I can help with testing
        - label: I can help with documentation
