# MCP Level 3 - Validation Engine Policy
# Defines governance policies, access control, and compliance rules

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EnginePolicy
metadata:
  name: validation-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Validation Engine Governance and Access Control Policies"
  labels:
    engine-type: validation
    policy-type: governance
    compliance: required
  annotations:
    mcp.ninjatech.ai/policy-version: "1.0.0"
    mcp.ninjatech.ai/enforcement: "strict"

# ============================================================================
# ROLE-BASED ACCESS CONTROL (RBAC)
# ============================================================================

rbac:
  roles:
    - name: validation-admin
      description: "Full administrative access"
      permissions:
        - resource: "*"
          actions: ["*"]
      subjects:
        - kind: User
          names: ["admin@ninjatech.ai"]
    
    - name: qa-engineer
      description: "Quality assurance engineer"
      permissions:
        - resource: "schemas"
          actions: ["create", "read", "update", "delete"]
        - resource: "tests"
          actions: ["create", "read", "update", "delete", "execute"]
        - resource: "reports"
          actions: ["create", "read"]
      subjects:
        - kind: Group
          names: ["qa-engineers"]
    
    - name: data-validator
      description: "Data validation specialist"
      permissions:
        - resource: "schemas"
          actions: ["read", "validate"]
        - resource: "quality-rules"
          actions: ["read", "validate"]
        - resource: "reports"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["data-validators"]
    
    - name: validation-viewer
      description: "Read-only access"
      permissions:
        - resource: "*"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["viewers"]

authentication:
  methods:
    - type: oauth2
      enabled: true
    - type: api-key
      enabled: true

authorization:
  engine: "opa"
  evaluation:
    mode: "strict"
    deny_by_default: true

# ============================================================================
# VALIDATION POLICIES
# ============================================================================

validation:
  schema_validation:
    required_for:
      - "production data"
      - "api requests"
      - "data ingestion"
    
    enforcement:
      mode: "strict"
      on_failure: "reject"
  
  quality_validation:
    thresholds:
      - metric: "completeness"
        min_value: 0.95
        severity: "error"
      
      - metric: "accuracy"
        min_value: 0.90
        severity: "warning"
      
      - metric: "consistency"
        min_value: 0.95
        severity: "error"
  
  test_execution:
    required_for:
      - "production deployments"
      - "critical changes"
    
    coverage:
      minimum: 0.80
      target: 0.90

security:
  encryption:
    at_rest:
      enabled: true
      algorithm: "AES-256-GCM"
    in_transit:
      enabled: true
      protocol: "TLS 1.3"

compliance:
  frameworks:
    - name: "SOC2"
      enabled: true
  
  audit:
    enabled: true
    retention: 365d

enforcement:
  mode: "strict"
  violations:
    - severity: "critical"
      action: "block"

documentation:
  policy_guide: "https://docs.ninjatech.ai/mcp/validation-engine/policies"