# MCP Level 3 - Validation Engine Dependency Graph

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineGraph
metadata:
  name: validation-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Validation Engine dependency graph"
  labels:
    engine-type: validation
    graph-type: dependency

nodes:
  - id: validation-api-service
    type: service
    category: api
    name: "Validation API Service"
    properties:
      port: 8080
      replicas: 3
      criticality: high
  
  - id: schema-validator
    type: service
    category: core
    name: "Schema Validator"
    properties:
      port: 8081
      replicas: 5
      criticality: high
  
  - id: quality-validator
    type: service
    category: core
    name: "Quality Validator"
    properties:
      port: 8082
      replicas: 3
      criticality: high
  
  - id: test-runner
    type: service
    category: core
    name: "Test Runner"
    properties:
      port: 8083
      replicas: 5
      criticality: high
  
  - id: evaluation-service
    type: service
    category: core
    name: "Evaluation Service"
    properties:
      port: 8084
      replicas: 3
      criticality: medium
  
  - id: schema-registry
    type: datastore
    category: storage
    name: "Schema Registry"
    properties:
      provider: confluent
      criticality: critical
  
  - id: test-results-store
    type: datastore
    category: storage
    name: "Test Results Store"
    properties:
      provider: postgresql
      criticality: high
  
  - id: metrics-store
    type: datastore
    category: storage
    name: "Metrics Store"
    properties:
      provider: prometheus
      criticality: medium

edges:
  - source: validation-api-service
    target: schema-validator
    type: synchronous
    protocol: http
    properties:
      latency: 30ms
      throughput: 2000rps
  
  - source: validation-api-service
    target: quality-validator
    type: synchronous
    protocol: http
    properties:
      latency: 50ms
      throughput: 1000rps
  
  - source: schema-validator
    target: schema-registry
    type: synchronous
    protocol: http
    properties:
      latency: 20ms
      throughput: 5000rps
  
  - source: quality-validator
    target: test-results-store
    type: synchronous
    protocol: postgresql
    properties:
      latency: 30ms
      throughput: 2000rps
  
  - source: test-runner
    target: test-results-store
    type: synchronous
    protocol: postgresql
    properties:
      latency: 50ms
      throughput: 1000rps
  
  - source: evaluation-service
    target: metrics-store
    type: synchronous
    protocol: prometheus
    properties:
      latency: 20ms
      throughput: 500rps

dependency_matrix:
  services:
    - validation-api-service
    - schema-validator
    - quality-validator
    - test-runner
    - evaluation-service
  
  matrix:
    validation-api-service: [0, 1, 1, 1, 0]
    schema-validator: [0, 0, 0, 0, 0]
    quality-validator: [0, 0, 0, 0, 0]
    test-runner: [0, 0, 0, 0, 0]
    evaluation-service: [0, 0, 0, 0, 0]

data_flows:
  - name: validation-flow
    steps:
      - step: 1
        component: validation-api-service
        action: "Receive validation request"
      - step: 2
        component: schema-validator
        action: "Validate schema"
      - step: 3
        component: quality-validator
        action: "Validate quality"

critical_paths:
  - name: validation-critical-path
    path:
      - validation-api-service
      - schema-validator
      - schema-registry
    total_latency: 50ms

performance:
  throughput:
    validations_per_second: 2000
  latency:
    p50: 50ms
    p95: 150ms
    p99: 300ms

documentation:
  architecture_diagram: "https://docs.ninjatech.ai/mcp/validation-engine/architecture"
