# MCP Level 3 - Validation Engine Specification
# Defines API specifications, interface contracts, and integration patterns

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineSpec
metadata:
  name: validation-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Validation Engine API Specification"
  labels:
    engine-type: validation
    capability: quality-assurance
    tier: core
  annotations:
    mcp.ninjatech.ai/spec-version: "1.0.0"
    mcp.ninjatech.ai/last-updated: "2024-01-15"

# ============================================================================
# API SPECIFICATIONS
# ============================================================================

api:
  rest:
    baseUrl: "/api/v1/validation"
    version: "1.0.0"
    
    endpoints:
      # Schema Validation
      - path: "/schemas"
        method: POST
        operationId: createSchema
        summary: "Create a validation schema"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [name, type, definition]
                properties:
                  name:
                    type: string
                  type:
                    type: string
                    enum: [json_schema, avro, protobuf, xml_schema]
                  definition:
                    type: object
        responses:
          201:
            description: "Schema created"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/SchemaResponse"
      
      - path: "/schemas/{schema_id}/validate"
        method: POST
        operationId: validateAgainstSchema
        summary: "Validate data against a schema"
        parameters:
          - name: schema_id
            in: path
            required: true
            schema:
              type: string
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
        responses:
          200:
            description: "Validation result"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ValidationResult"
      
      # Data Quality Validation
      - path: "/quality/validate"
        method: POST
        operationId: validateDataQuality
        summary: "Validate data quality"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [data, rules]
                properties:
                  data:
                    type: object
                  rules:
                    type: array
                    items:
                      $ref: "#/components/schemas/QualityRule"
        responses:
          200:
            description: "Quality validation result"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/QualityValidationResult"
      
      # Test Case Management
      - path: "/tests"
        method: POST
        operationId: createTestCase
        summary: "Create a test case"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [name, type, assertions]
                properties:
                  name:
                    type: string
                  type:
                    type: string
                    enum: [unit, integration, e2e, performance]
                  assertions:
                    type: array
        responses:
          201:
            description: "Test case created"
      
      - path: "/tests/{test_id}/execute"
        method: POST
        operationId: executeTest
        summary: "Execute a test case"
        parameters:
          - name: test_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Test execution result"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/TestResult"
      
      # Validation Reports
      - path: "/reports"
        method: POST
        operationId: generateValidationReport
        summary: "Generate a validation report"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  scope:
                    type: object
                  metrics:
                    type: array
        responses:
          201:
            description: "Report generated"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ValidationReport"
      
      # Metrics and Scoring
      - path: "/metrics/calculate"
        method: POST
        operationId: calculateMetrics
        summary: "Calculate quality metrics"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                  metric_types:
                    type: array
                    items:
                      type: string
        responses:
          200:
            description: "Calculated metrics"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/MetricScores"
      
      # Evaluation Framework
      - path: "/evaluate"
        method: POST
        operationId: evaluateModel
        summary: "Evaluate model performance"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [predictions, ground_truth]
                properties:
                  predictions:
                    type: array
                  ground_truth:
                    type: array
                  metrics:
                    type: array
        responses:
          200:
            description: "Evaluation results"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/EvaluationResult"
  
  grpc:
    package: "mcp.validation.v1"
    services:
      - name: ValidationService
        methods:
          - name: ValidateSchema
            input: SchemaValidationRequest
            output: ValidationResult
          
          - name: ValidateQuality
            input: QualityValidationRequest
            output: QualityValidationResult
          
          - name: ExecuteTest
            input: TestExecutionRequest
            output: TestResult
  
  events:
    protocol: kafka
    topics:
      - name: validation.schema.validated
        schema: SchemaValidatedEvent
        partitions: 10
        retention: 7d
      
      - name: validation.test.executed
        schema: TestExecutedEvent
        partitions: 10
        retention: 30d
      
      - name: validation.quality.failed
        schema: QualityFailedEvent
        partitions: 5
        retention: 30d

# ============================================================================
# DATA SCHEMAS
# ============================================================================

components:
  schemas:
    SchemaResponse:
      type: object
      properties:
        schema_id:
          type: string
        name:
          type: string
        type:
          type: string
        created_at:
          type: string
          format: date-time
    
    ValidationResult:
      type: object
      properties:
        valid:
          type: boolean
        errors:
          type: array
        warnings:
          type: array
    
    QualityRule:
      type: object
      properties:
        rule_id:
          type: string
        condition:
          type: string
        severity:
          type: string
    
    QualityValidationResult:
      type: object
      properties:
        passed:
          type: boolean
        score:
          type: number
        violations:
          type: array
    
    TestResult:
      type: object
      properties:
        test_id:
          type: string
        status:
          type: string
          enum: [passed, failed, skipped]
        duration:
          type: number
        assertions:
          type: array
    
    ValidationReport:
      type: object
      properties:
        report_id:
          type: string
        summary:
          type: object
        details:
          type: array
    
    MetricScores:
      type: object
      properties:
        accuracy:
          type: number
        precision:
          type: number
        recall:
          type: number
        f1_score:
          type: number
    
    EvaluationResult:
      type: object
      properties:
        metrics:
          type: object
        confusion_matrix:
          type: array
        roc_curve:
          type: object

contracts:
  sla:
    availability: 99.9%
    latency:
      p50: 100ms
      p95: 300ms
      p99: 500ms

integration:
  upstream:
    - service: schema-registry
      protocol: rest
    - service: test-runner
      protocol: grpc
  
  downstream:
    - service: metrics-store
      protocol: prometheus

versioning:
  strategy: semantic
  current: 1.0.0
  supported: [1.0.0]

documentation:
  openapi: "https://docs.ninjatech.ai/mcp/validation-engine/openapi.yaml"