version: "2.0.0"
semantic_role: workflow_definition
artifact_type: flow
semantic_root: false
module: integration-extension

description: |
  Complete workflow definition for the Integration & Extension pipeline.
  Defines end-to-end integration flow from request routing through adapter
  execution to response delivery with middleware, plugins, and event handling.

workflow:
  name: "integration-workflow"
  version: "2.0.0"
  type: "request-response"
  execution_mode: "sequential"
  
triggers:
  - type: "event"
    events: ["request_received", "webhook_triggered", "event_published"]
  - type: "api"
    endpoints: ["/api/v1/integrate"]
  - type: "manual"
    enabled: true

stages:
  # Stage 1: Request Reception
  request_reception:
    name: "Request Reception"
    type: "sequential"
    description: "Receive and validate incoming requests"
    tasks:
      receive_request:
        name: "Receive Request"
        component: "IntegrationBridge"
        action: "receiveRequest"
        inputs:
          - "raw_request"
        outputs:
          - "parsed_request"
        performance:
          timeout: "5s"
      validate_request:
        name: "Validate Request"
        component: "IntegrationBridge"
        action: "validateRequest"
        inputs:
          - "parsed_request"
        outputs:
          - "validated_request"
        performance:
          timeout: "1s"
    on_success: "middleware_processing"
    on_failure: "error_handling"

  # Stage 2: Middleware Processing
  middleware_processing:
    name: "Middleware Processing"
    type: "sequential"
    description: "Execute middleware chain"
    tasks:
      execute_middleware:
        name: "Execute Middleware Chain"
        component: "MiddlewareChain"
        action: "execute"
        inputs:
          - "validated_request"
        middlewares:
          - "authentication"
          - "authorization"
          - "rate_limiting"
          - "logging"
          - "metrics"
        outputs:
          - "processed_request"
        performance:
          timeout: "2s"
    on_success: "adapter_selection"
    on_failure: "error_handling"

  # Stage 3: Adapter Selection
  adapter_selection:
    name: "Adapter Selection"
    type: "sequential"
    description: "Select appropriate adapter"
    tasks:
      determine_protocol:
        name: "Determine Protocol"
        component: "AdapterRegistry"
        action: "determineProtocol"
        inputs:
          - "processed_request"
        outputs:
          - "protocol_type"
        performance:
          timeout: "100ms"
      select_adapter:
        name: "Select Adapter"
        component: "AdapterRegistry"
        action: "getAdapter"
        inputs:
          - "protocol_type"
        outputs:
          - "selected_adapter"
        performance:
          timeout: "10ms"
    on_success: "adapter_execution"
    on_failure: "error_handling"

  # Stage 4: Adapter Execution
  adapter_execution:
    name: "Adapter Execution"
    type: "conditional"
    description: "Execute selected adapter"
    condition: "selected_adapter != null"
    tasks:
      execute_rest:
        name: "Execute REST Adapter"
        component: "RESTAdapter"
        action: "request"
        condition: "protocol_type == 'rest'"
        inputs:
          - "processed_request"
        outputs:
          - "adapter_response"
        performance:
          timeout: "30s"
      execute_graphql:
        name: "Execute GraphQL Adapter"
        component: "GraphQLAdapter"
        action: "query"
        condition: "protocol_type == 'graphql'"
        inputs:
          - "processed_request"
        outputs:
          - "adapter_response"
        performance:
          timeout: "30s"
      execute_grpc:
        name: "Execute gRPC Adapter"
        component: "GRPCAdapter"
        action: "unaryCall"
        condition: "protocol_type == 'grpc'"
        inputs:
          - "processed_request"
        outputs:
          - "adapter_response"
        performance:
          timeout: "30s"
      execute_webhook:
        name: "Execute Webhook Adapter"
        component: "WebhookAdapter"
        action: "send"
        condition: "protocol_type == 'webhook'"
        inputs:
          - "processed_request"
        outputs:
          - "adapter_response"
        performance:
          timeout: "30s"
    on_success: "plugin_execution"
    on_failure: "error_handling"

  # Stage 5: Plugin Execution
  plugin_execution:
    name: "Plugin Execution"
    type: "sequential"
    description: "Execute registered plugins"
    tasks:
      execute_pre_response_hooks:
        name: "Execute Pre-Response Hooks"
        component: "PluginSystem"
        action: "executeHook"
        inputs:
          hook_name: "pre_response"
          context:
            - "adapter_response"
        outputs:
          - "plugin_response"
        performance:
          timeout: "5s"
    on_success: "event_publishing"
    on_failure: "error_handling"

  # Stage 6: Event Publishing
  event_publishing:
    name: "Event Publishing"
    type: "parallel"
    description: "Publish integration events"
    tasks:
      publish_success_event:
        name: "Publish Success Event"
        component: "EventBridge"
        action: "publish"
        inputs:
          event:
            type: "integration.success"
            data: "plugin_response"
        outputs:
          - "event_id"
        performance:
          timeout: "1s"
      publish_metrics:
        name: "Publish Metrics"
        component: "MetricsCollector"
        action: "collect"
        inputs:
          metrics:
            - "integration_duration"
            - "adapter_latency"
            - "plugin_execution_time"
        performance:
          timeout: "500ms"
    on_success: "response_delivery"
    on_failure: "error_handling"

  # Stage 7: Response Delivery
  response_delivery:
    name: "Response Delivery"
    type: "sequential"
    description: "Deliver response to client"
    tasks:
      format_response:
        name: "Format Response"
        component: "IntegrationBridge"
        action: "formatResponse"
        inputs:
          - "plugin_response"
        outputs:
          - "formatted_response"
        performance:
          timeout: "1s"
      deliver_response:
        name: "Deliver Response"
        component: "IntegrationBridge"
        action: "deliverResponse"
        inputs:
          - "formatted_response"
        outputs:
          - "delivery_status"
        performance:
          timeout: "5s"
    on_success: "completion"
    on_failure: "error_handling"

  # Stage 8: Error Handling
  error_handling:
    name: "Error Handling"
    type: "sequential"
    description: "Handle errors and failures"
    tasks:
      log_error:
        name: "Log Error"
        component: "Logger"
        action: "error"
        inputs:
          - "error_details"
      publish_error_event:
        name: "Publish Error Event"
        component: "EventBridge"
        action: "publish"
        inputs:
          event:
            type: "integration.error"
            data: "error_details"
      retry_or_fail:
        name: "Retry or Fail"
        action: "decision"
        conditions:
          - condition: "retry_count < 3 && error.retryable"
            action: "retry"
            target: "adapter_execution"
          - condition: "retry_count >= 3 || !error.retryable"
            action: "fail"
            target: "completion"

  # Stage 9: Completion
  completion:
    name: "Workflow Completion"
    type: "sequential"
    description: "Finalize workflow execution"
    tasks:
      record_metrics:
        name: "Record Workflow Metrics"
        component: "MetricsCollector"
        action: "collect"
        metrics:
          - "workflow_duration"
          - "workflow_success_rate"
      cleanup:
        name: "Cleanup Resources"
        action: "cleanup"

execution:
  parallelism:
    max_concurrent_stages: 2
    max_concurrent_tasks: 5
  retry_policy:
    max_attempts: 3
    backoff: "exponential"
    initial_delay: "1s"
    max_delay: "30s"
  timeout:
    workflow: "2m"
    stage: "1m"
    task: "30s"
  error_handling:
    strategy: "retry_then_fail"
    max_errors: 3

monitoring:
  metrics:
    - name: "integration_workflow_executions_total"
      type: "counter"
      labels: ["status", "protocol"]
    - name: "integration_workflow_duration_seconds"
      type: "histogram"
      buckets: [0.1, 0.5, 1, 5, 10, 30, 60, 120]
    - name: "integration_adapter_executions_total"
      type: "counter"
      labels: ["adapter_type", "status"]
  alerts:
    - name: "WorkflowFailure"
      condition: "workflow_success_rate < 0.95"
      severity: "critical"
    - name: "HighLatency"
      condition: "workflow_duration_p99 > 60s"
      severity: "warning"

metadata:
  created_at: "2025-01-11T12:30:00Z"
  updated_at: "2025-01-11T12:30:00Z"
  version: "2.0.0"
  status: "active"
  total_stages: 9
  total_tasks: 20
  execution_mode: "sequential"
  maintainer: "MachineNativeOps Team"
  
performance_targets:
  workflow_duration_p50: "< 1s"
  workflow_duration_p99: "< 60s"
  success_rate: "> 99%"