/**
 * Holy Grail Agent Types
 * Type definitions for AI expert agents
 */

/**
 * Signal levels for agent insights
 */
export type InsightSignal = 'info' | 'warn' | 'error' | 'success';

/**
 * Agent insight - a single observation or recommendation from an agent
 */
export interface AgentInsight {
  title: string;
  description: string;
  signal: InsightSignal;
  metadata?: Record<string, unknown>;
}

/**
 * Context passed to agents during execution
 */
export interface AgentContext {
  runId: string;
  timestamp: Date;
  payload?: Record<string, unknown>;
  parameters?: Record<string, unknown>;
  environment?: string;
}

/**
 * Report generated by an agent after execution
 */
export interface AgentReport {
  agent: string;
  insights: AgentInsight[];
  generatedAt: Date;
  duration?: number;
  metadata?: Record<string, unknown>;
}

/**
 * Module interface that all agents must implement
 */
export interface AgentModule {
  readonly name: string;
  run(context: AgentContext): Promise<AgentReport>;
}
