version: "2.0.0"
semantic_role: governance_policies
artifact_type: policy
semantic_root: false
module: integration-extension

description: |
  Complete governance policies for the Integration & Extension module.
  Defines RBAC roles, security policies, rate limiting, and operational
  governance for adapters, plugins, middleware, and extensions.

# ============================================================================
# RBAC (Role-Based Access Control)
# ============================================================================

rbac:
  roles:
    integration_admin:
      description: "Full administrative access to integration system"
      permissions:
        - "adapter:*"
        - "plugin:*"
        - "middleware:*"
        - "extension:*"
        - "event:*"
      scope: "global"
      
    adapter_manager:
      description: "Manage protocol adapters"
      permissions:
        - "adapter:create"
        - "adapter:read"
        - "adapter:update"
        - "adapter:delete"
        - "adapter:configure"
      scope: "namespace"
      
    plugin_developer:
      description: "Develop and manage plugins"
      permissions:
        - "plugin:create"
        - "plugin:read"
        - "plugin:update"
        - "plugin:test"
        - "plugin:publish"
      scope: "namespace"
      
    extension_user:
      description: "Install and use extensions"
      permissions:
        - "extension:read"
        - "extension:install"
        - "extension:activate"
        - "extension:deactivate"
      scope: "namespace"
      
    integration_viewer:
      description: "Read-only access to integration system"
      permissions:
        - "adapter:read"
        - "plugin:read"
        - "extension:read"
        - "event:read"
      scope: "namespace"

  role_bindings:
    - role: "integration_admin"
      subjects:
        - type: "group"
          name: "platform-admins"
        - type: "group"
          name: "integration-team"
          
    - role: "adapter_manager"
      subjects:
        - type: "group"
          name: "devops-team"
        - type: "group"
          name: "api-team"
          
    - role: "plugin_developer"
      subjects:
        - type: "group"
          name: "developers"
        - type: "group"
          name: "plugin-team"

# ============================================================================
# SECURITY POLICIES
# ============================================================================

security:
  adapter_security:
    authentication:
      required: true
      methods: ["bearer", "apikey", "oauth2", "mutual_tls"]
      
    authorization:
      model: "rbac"
      default_deny: true
      
    encryption:
      in_transit:
        enabled: true
        protocol: "TLS 1.3"
        
    rate_limiting:
      enabled: true
      default_limit: "1000 req/min"
      
  plugin_security:
    sandbox:
      enabled: true
      isolation_level: "process"
      
    permissions:
      required: true
      approval_required: true
      
    code_signing:
      required: true
      algorithm: "RSA-4096"
      
    resource_limits:
      memory: "512 MB"
      cpu: "0.5 cores"
      
  extension_security:
    verification:
      required: true
      trusted_sources: ["official", "verified"]
      
    scanning:
      enabled: true
      scan_on_install: true
      
    updates:
      automatic: false
      approval_required: true

# ============================================================================
# RATE LIMITING & QUOTAS
# ============================================================================

rate_limits:
  rest_adapter:
    per_service: "10000 req/sec"
    per_endpoint: "1000 req/sec"
    burst: "2x"
    
  graphql_adapter:
    per_service: "5000 queries/sec"
    complexity_limit: 1000
    depth_limit: 10
    
  grpc_adapter:
    per_service: "50000 req/sec"
    stream_limit: 1000
    
  webhook_adapter:
    per_service: "1000 webhooks/sec"
    batch_size: 100
    
  event_bridge:
    per_service: "100000 events/sec"
    per_topic: "10000 events/sec"

quotas:
  adapters:
    max_per_namespace: 100
    max_connections: 1000
    
  plugins:
    max_per_namespace: 50
    max_active: 20
    
  extensions:
    max_per_namespace: 30
    max_storage: "1 GB"
    
  middleware:
    max_per_chain: 10
    max_chains: 50

# ============================================================================
# OPERATIONAL GOVERNANCE
# ============================================================================

governance:
  adapter_lifecycle:
    approval_required:
      - "production_deployment"
      - "configuration_change"
    testing_required: true
    rollback_plan: "required"
    
  plugin_lifecycle:
    review_required: true
    testing_required: true
    approval_required: true
    
  extension_lifecycle:
    verification_required: true
    approval_required: true
    
  change_management:
    approval_levels:
      development: 0
      staging: 1
      production: 2
    rollback_plan: "required"

# ============================================================================
# COMPLIANCE
# ============================================================================

compliance:
  data_protection:
    encryption_required: true
    pii_handling: "mask"
    
  audit:
    events:
      - "adapter_created"
      - "adapter_configured"
      - "plugin_loaded"
      - "extension_installed"
      - "webhook_sent"
    retention: "1 year"
    
  monitoring:
    metrics_required: true
    logging_required: true
    tracing_required: true

# ============================================================================
# QUALITY OF SERVICE
# ============================================================================

qos:
  availability:
    target: "99.9%"
    measurement: "monthly"
    
  performance:
    rest_adapter_p99: "< 500ms"
    grpc_adapter_p99: "< 100ms"
    event_bridge_p99: "< 20ms"
    
  reliability:
    error_rate: "< 0.1%"
    retry_success_rate: "> 95%"

metadata:
  created_at: "2025-01-10T14:00:00Z"
  updated_at: "2025-01-11T11:45:00Z"
  version: "2.0.0"
  status: "active"
  rbac_roles: 5
  security_controls: 15
  maintainer: "MachineNativeOps Team"