# MCP Level 3 - Execution Engine Policy
# Defines governance policies, access control, and compliance rules

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EnginePolicy
metadata:
  name: execution-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Execution Engine Governance and Access Control Policies"
  labels:
    engine-type: execution
    policy-type: governance
    compliance: required
  annotations:
    mcp.ninjatech.ai/policy-version: "1.0.0"
    mcp.ninjatech.ai/enforcement: "strict"

# ============================================================================
# ROLE-BASED ACCESS CONTROL (RBAC)
# ============================================================================

rbac:
  roles:
    - name: execution-admin
      description: "Full administrative access"
      permissions:
        - resource: "*"
          actions: ["*"]
      subjects:
        - kind: User
          names: ["admin@ninjatech.ai"]
    
    - name: execution-operator
      description: "Execute and monitor plans"
      permissions:
        - resource: "plans"
          actions: ["read", "execute"]
        - resource: "executions"
          actions: ["read", "cancel"]
        - resource: "transactions"
          actions: ["create", "commit", "rollback"]
      subjects:
        - kind: Group
          names: ["operators"]
    
    - name: execution-developer
      description: "Create and test execution plans"
      permissions:
        - resource: "plans"
          actions: ["create", "read", "update", "delete"]
        - resource: "executions"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["developers"]
    
    - name: execution-viewer
      description: "Read-only access"
      permissions:
        - resource: "*"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["viewers"]

authentication:
  methods:
    - type: oauth2
      enabled: true
    - type: api-key
      enabled: true

authorization:
  engine: "opa"
  evaluation:
    mode: "strict"
    deny_by_default: true

# ============================================================================
# EXECUTION POLICIES
# ============================================================================

execution:
  resource_limits:
    - scope: "execution"
      limits:
        max_duration: 3600
        max_memory: "4Gi"
        max_cpu: "2"
    
    - scope: "transaction"
      limits:
        max_duration: 300
        max_operations: 1000
  
  retry:
    default:
      max_attempts: 3
      backoff: "exponential"
    
    by_error_type:
      - error: "TransientError"
        max_attempts: 5
      - error: "PermanentError"
        max_attempts: 0
  
  timeout:
    default: 300
    by_operation_type:
      - type: "data_processing"
        timeout: 1800
      - type: "api_call"
        timeout: 30

# ============================================================================
# TRANSACTION POLICIES
# ============================================================================

transaction:
  isolation_levels:
    allowed: [read_committed, repeatable_read, serializable]
    default: read_committed
  
  distributed:
    protocol: "2PC"  # Two-Phase Commit
    timeout: 60
    coordinator_timeout: 120

security:
  encryption:
    at_rest:
      enabled: true
      algorithm: "AES-256-GCM"
    in_transit:
      enabled: true
      protocol: "TLS 1.3"

compliance:
  frameworks:
    - name: "SOC2"
      enabled: true
  
  audit:
    enabled: true
    retention: 365d

enforcement:
  mode: "strict"
  violations:
    - severity: "critical"
      action: "block"

documentation:
  policy_guide: "https://docs.ninjatech.ai/mcp/execution-engine/policies"