# MCP Level 3 - Execution Engine Dependency Graph

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineGraph
metadata:
  name: execution-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Execution Engine dependency graph"
  labels:
    engine-type: execution
    graph-type: dependency

nodes:
  - id: execution-api-service
    type: service
    category: api
    name: "Execution API Service"
    properties:
      port: 8080
      replicas: 3
      criticality: high
  
  - id: execution-coordinator
    type: service
    category: core
    name: "Execution Coordinator"
    properties:
      port: 8081
      replicas: 3
      criticality: critical
  
  - id: task-executor
    type: service
    category: core
    name: "Task Executor"
    properties:
      port: 8082
      replicas: 10
      criticality: critical
  
  - id: transaction-manager
    type: service
    category: core
    name: "Transaction Manager"
    properties:
      port: 8083
      replicas: 3
      criticality: critical
  
  - id: state-store
    type: datastore
    category: storage
    name: "State Store"
    properties:
      provider: redis
      criticality: critical
  
  - id: execution-log-store
    type: datastore
    category: storage
    name: "Execution Log Store"
    properties:
      provider: s3
      criticality: high
  
  - id: lock-service
    type: infrastructure
    category: coordination
    name: "Lock Service"
    properties:
      provider: etcd
      criticality: critical

edges:
  - source: execution-api-service
    target: execution-coordinator
    type: synchronous
    protocol: grpc
    properties:
      latency: 20ms
      throughput: 1000rps
  
  - source: execution-coordinator
    target: task-executor
    type: asynchronous
    protocol: kafka
    properties:
      topic: "execution.tasks"
  
  - source: execution-coordinator
    target: state-store
    type: synchronous
    protocol: redis
    properties:
      latency: 5ms
      throughput: 5000rps
  
  - source: task-executor
    target: state-store
    type: synchronous
    protocol: redis
    properties:
      latency: 5ms
      throughput: 10000rps
  
  - source: task-executor
    target: execution-log-store
    type: asynchronous
    protocol: s3
    properties:
      latency: 100ms
  
  - source: transaction-manager
    target: lock-service
    type: synchronous
    protocol: grpc
    properties:
      latency: 10ms
      throughput: 2000rps
  
  - source: transaction-manager
    target: state-store
    type: synchronous
    protocol: redis
    properties:
      latency: 5ms
      throughput: 5000rps

dependency_matrix:
  services:
    - execution-api-service
    - execution-coordinator
    - task-executor
    - transaction-manager
  
  matrix:
    execution-api-service: [0, 1, 0, 0]
    execution-coordinator: [0, 0, 1, 0]
    task-executor: [0, 0, 0, 0]
    transaction-manager: [0, 0, 0, 0]

data_flows:
  - name: execution-flow
    steps:
      - step: 1
        component: execution-api-service
        action: "Receive execution request"
      - step: 2
        component: execution-coordinator
        action: "Create execution plan"
      - step: 3
        component: task-executor
        action: "Execute tasks"

critical_paths:
  - name: execution-critical-path
    path:
      - execution-api-service
      - execution-coordinator
      - task-executor
      - state-store
    total_latency: 30ms

performance:
  throughput:
    executions_per_second: 1000
  latency:
    p50: 30ms
    p95: 100ms
    p99: 200ms

documentation:
  architecture_diagram: "https://docs.ninjatech.ai/mcp/execution-engine/architecture"
