# MCP Level 3 - Execution Engine Bundle

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineBundle
metadata:
  name: execution-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Execution Engine deployment bundle"
  labels:
    engine-type: execution
    deployment-tier: core
    criticality: critical

components:
  services:
    - name: execution-api-service
      type: rest-api
      version: 1.0.0
      image: "ninjatech/execution-api:1.0.0"
      port: 8080
      replicas: 3
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
    
    - name: execution-coordinator
      type: service
      version: 1.0.0
      image: "ninjatech/execution-coordinator:1.0.0"
      port: 8081
      replicas: 3
      resources:
        requests:
          cpu: "1000m"
          memory: "2Gi"
        limits:
          cpu: "4000m"
          memory: "8Gi"
    
    - name: task-executor
      type: service
      version: 1.0.0
      image: "ninjatech/task-executor:1.0.0"
      port: 8082
      replicas: 10
      resources:
        requests:
          cpu: "2000m"
          memory: "4Gi"
        limits:
          cpu: "8000m"
          memory: "16Gi"
    
    - name: transaction-manager
      type: service
      version: 1.0.0
      image: "ninjatech/transaction-manager:1.0.0"
      port: 8083
      replicas: 3
      resources:
        requests:
          cpu: "1000m"
          memory: "2Gi"
        limits:
          cpu: "4000m"
          memory: "8Gi"
  
  datastores:
    - name: state-store
      type: key-value
      provider: "redis"
      version: "7.x"
      configuration:
        replicas: 3
        cluster_mode: true
      resources:
        memory: "32Gi"
    
    - name: execution-log-store
      type: object-storage
      provider: "s3"
      configuration:
        bucket: "execution-logs"
        retention: 90d
      resources:
        storage: "5Ti"
    
    - name: lock-service
      type: distributed-lock
      provider: "etcd"
      version: "3.x"
      configuration:
        replicas: 3
      resources:
        memory: "8Gi"

deployment:
  strategy:
    type: "rolling"
  
  scaling:
    horizontal:
      enabled: true
      min_replicas: 3
      max_replicas: 50
      metrics:
        - type: cpu
          target: 70
        - type: custom
          name: execution_queue_depth
          target: 100
  
  quotas:
    cpu: "200"
    memory: "400Gi"
    storage: "10Ti"

environments:
  production:
    replicas: 3
    resources:
      cpu: "200"
      memory: "400Gi"

secrets:
  - name: state-store-credentials
    type: credentials
    provider: vault
    path: "secret/execution/state-store"

health_checks:
  liveness:
    http_get:
      path: "/health/live"
      port: 8080
    initial_delay: 30s
    period: 10s

observability:
  metrics:
    enabled: true
    provider: prometheus
    custom_metrics:
      - name: executions_total
        type: counter
      - name: execution_duration
        type: histogram
  logging:
    enabled: true
    provider: elasticsearch
  tracing:
    enabled: true
    provider: jaeger

security:
  pod_security:
    run_as_non_root: true

backup:
  enabled: true
  schedule: "0 2 * * *"
  retention: 30d

documentation:
  deployment_guide: "https://docs.ninjatech.ai/mcp/execution-engine/deployment"
