# MCP Level 3 - Execution Engine Specification
# Defines API specifications, interface contracts, and integration patterns

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineSpec
metadata:
  name: execution-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Execution Engine API Specification"
  labels:
    engine-type: execution
    capability: task-execution
    tier: core
  annotations:
    mcp.ninjatech.ai/spec-version: "1.0.0"
    mcp.ninjatech.ai/last-updated: "2024-01-15"

# ============================================================================
# API SPECIFICATIONS
# ============================================================================

api:
  rest:
    baseUrl: "/api/v1/execution"
    version: "1.0.0"
    
    endpoints:
      # Execution Plan Management
      - path: "/plans"
        method: POST
        operationId: createExecutionPlan
        summary: "Create a new execution plan"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [name, steps]
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  steps:
                    type: array
                    items:
                      $ref: "#/components/schemas/ExecutionStep"
                  strategy:
                    type: string
                    enum: [sequential, parallel, conditional]
        responses:
          201:
            description: "Execution plan created"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ExecutionPlanResponse"
      
      - path: "/plans/{plan_id}/execute"
        method: POST
        operationId: executePlan
        summary: "Execute a plan"
        parameters:
          - name: plan_id
            in: path
            required: true
            schema:
              type: string
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  parameters:
                    type: object
                  context:
                    type: object
        responses:
          202:
            description: "Execution started"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ExecutionResponse"
      
      # Execution Monitoring
      - path: "/executions/{execution_id}"
        method: GET
        operationId: getExecution
        summary: "Get execution status"
        parameters:
          - name: execution_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Execution details"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ExecutionResponse"
      
      - path: "/executions/{execution_id}/cancel"
        method: POST
        operationId: cancelExecution
        summary: "Cancel a running execution"
        parameters:
          - name: execution_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Execution cancelled"
      
      # Transaction Management
      - path: "/transactions"
        method: POST
        operationId: beginTransaction
        summary: "Begin a new transaction"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  isolation_level:
                    type: string
                    enum: [read_uncommitted, read_committed, repeatable_read, serializable]
                  timeout:
                    type: integer
        responses:
          201:
            description: "Transaction started"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/TransactionResponse"
      
      - path: "/transactions/{transaction_id}/commit"
        method: POST
        operationId: commitTransaction
        summary: "Commit a transaction"
        parameters:
          - name: transaction_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Transaction committed"
      
      - path: "/transactions/{transaction_id}/rollback"
        method: POST
        operationId: rollbackTransaction
        summary: "Rollback a transaction"
        parameters:
          - name: transaction_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Transaction rolled back"
      
      # Rollback Management
      - path: "/rollbacks"
        method: POST
        operationId: createRollbackPlan
        summary: "Create a rollback plan"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [execution_id, steps]
                properties:
                  execution_id:
                    type: string
                  steps:
                    type: array
                  strategy:
                    type: string
        responses:
          201:
            description: "Rollback plan created"
      
      - path: "/rollbacks/{rollback_id}/execute"
        method: POST
        operationId: executeRollback
        summary: "Execute a rollback"
        parameters:
          - name: rollback_id
            in: path
            required: true
            schema:
              type: string
        responses:
          202:
            description: "Rollback started"
      
      # Execution Logs
      - path: "/executions/{execution_id}/logs"
        method: GET
        operationId: getExecutionLogs
        summary: "Get execution logs"
        parameters:
          - name: execution_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Execution logs"
  
  grpc:
    package: "mcp.execution.v1"
    services:
      - name: ExecutionService
        methods:
          - name: ExecutePlan
            input: ExecutePlanRequest
            output: ExecutionResponse
          
          - name: StreamExecution
            input: StreamExecutionRequest
            output: stream ExecutionEvent
          
          - name: ManageTransaction
            input: TransactionRequest
            output: TransactionResponse
  
  events:
    protocol: kafka
    topics:
      - name: execution.started
        schema: ExecutionStartedEvent
        partitions: 10
        retention: 7d
      
      - name: execution.completed
        schema: ExecutionCompletedEvent
        partitions: 10
        retention: 30d
      
      - name: execution.failed
        schema: ExecutionFailedEvent
        partitions: 10
        retention: 30d
      
      - name: transaction.committed
        schema: TransactionCommittedEvent
        partitions: 5
        retention: 30d

# ============================================================================
# DATA SCHEMAS
# ============================================================================

components:
  schemas:
    ExecutionStep:
      type: object
      properties:
        step_id:
          type: string
        action:
          type: string
        parameters:
          type: object
        retry_policy:
          type: object
    
    ExecutionPlanResponse:
      type: object
      properties:
        plan_id:
          type: string
        name:
          type: string
        steps:
          type: array
        created_at:
          type: string
          format: date-time
    
    ExecutionResponse:
      type: object
      properties:
        execution_id:
          type: string
        plan_id:
          type: string
        status:
          type: string
          enum: [pending, running, completed, failed, cancelled]
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        results:
          type: object
    
    TransactionResponse:
      type: object
      properties:
        transaction_id:
          type: string
        status:
          type: string
        isolation_level:
          type: string

contracts:
  sla:
    availability: 99.95%
    latency:
      p50: 100ms
      p95: 500ms
      p99: 1000ms

integration:
  upstream:
    - service: state-store
      protocol: grpc
    - service: message-queue
      protocol: kafka
  
  downstream:
    - service: monitoring
      protocol: prometheus

versioning:
  strategy: semantic
  current: 1.0.0
  supported: [1.0.0]

documentation:
  openapi: "https://docs.ninjatech.ai/mcp/execution-engine/openapi.yaml"