# MCP Level 3 - Governance Engine Policy
# Defines governance policies, access control, and compliance rules

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EnginePolicy
metadata:
  name: governance-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Governance Engine Governance and Access Control Policies"
  labels:
    engine-type: governance
    policy-type: meta-governance
    compliance: required
  annotations:
    mcp.ninjatech.ai/policy-version: "1.0.0"
    mcp.ninjatech.ai/enforcement: "strict"

# ============================================================================
# ROLE-BASED ACCESS CONTROL (RBAC)
# ============================================================================

rbac:
  roles:
    # Governance Administrator
    - name: governance-admin
      description: "Full administrative access to governance engine"
      permissions:
        - resource: "*"
          actions: ["*"]
      subjects:
        - kind: User
          names: ["governance-admin@ninjatech.ai"]
        - kind: ServiceAccount
          names: ["governance-admin-sa"]
    
    # Policy Manager
    - name: policy-manager
      description: "Manage governance policies"
      permissions:
        - resource: "policies"
          actions: ["create", "read", "update", "delete"]
        - resource: "policy-evaluations"
          actions: ["read"]
        - resource: "audit-logs"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["policy-managers", "compliance-team"]
    
    # Compliance Officer
    - name: compliance-officer
      description: "Manage compliance and generate reports"
      permissions:
        - resource: "policies"
          actions: ["read"]
        - resource: "compliance-reports"
          actions: ["create", "read"]
        - resource: "audit-logs"
          actions: ["read"]
        - resource: "violations"
          actions: ["read", "investigate"]
      subjects:
        - kind: Group
          names: ["compliance-officers"]
    
    # Security Auditor
    - name: security-auditor
      description: "Audit access and review logs"
      permissions:
        - resource: "audit-logs"
          actions: ["read", "export"]
        - resource: "access-decisions"
          actions: ["read"]
        - resource: "policies"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["security-auditors", "internal-audit"]
    
    # Policy Enforcer (Service Account)
    - name: policy-enforcer
      description: "Automated policy enforcement"
      permissions:
        - resource: "policies"
          actions: ["read", "evaluate"]
        - resource: "access-checks"
          actions: ["create"]
        - resource: "audit-logs"
          actions: ["create"]
      subjects:
        - kind: ServiceAccount
          names: ["enforcer-sa"]

  roleBindings:
    - role: governance-admin
      subjects:
        - kind: User
          name: "governance-admin@ninjatech.ai"
      scope: global
    
    - role: policy-manager
      subjects:
        - kind: Group
          name: "compliance-team"
      scope: global
    
    - role: policy-enforcer
      subjects:
        - kind: ServiceAccount
          name: "enforcer-sa"
      scope: global

# ============================================================================
# AUTHENTICATION & AUTHORIZATION
# ============================================================================

authentication:
  methods:
    - type: oauth2
      enabled: true
      provider: "auth0"
      config:
        issuer: "https://auth.ninjatech.ai"
        audience: "governance-engine-api"
        scopes:
          - governance:read
          - governance:write
          - governance:admin
          - compliance:read
          - compliance:write
    
    - type: mutual-tls
      enabled: true
      ca_cert: "/etc/certs/ca.crt"
      verify_client: true
      required_for:
        - "policy-enforcement"
        - "audit-logging"
    
    - type: service-account
      enabled: true
      token_path: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  
  tokens:
    access_token:
      lifetime: 1800  # 30 minutes (shorter for governance)
      refresh: true
      refresh_lifetime: 3600
    
    service_account:
      auto_rotate: true
      rotation_period: 7d  # Weekly rotation

authorization:
  engine: "opa"
  
  evaluation:
    mode: "strict"
    cache_ttl: 60  # Shorter cache for governance
    deny_by_default: true
  
  abac:
    enabled: true
    attributes:
      - name: user.clearance_level
        type: integer
        values: [1, 2, 3, 4, 5]
      
      - name: policy.sensitivity
        type: string
        values: ["public", "internal", "confidential", "secret"]
      
      - name: action.risk_level
        type: string
        values: ["low", "medium", "high", "critical"]
      
      - name: time.business_hours
        type: boolean
    
    rules:
      - name: "high-risk-actions-require-approval"
        condition: "action.risk_level in ['high', 'critical']"
        effect: "require_approval"
        approvers: ["governance-admin"]
      
      - name: "secret-policy-access"
        condition: "policy.sensitivity == 'secret' AND user.clearance_level >= 4"
        effect: "allow"
      
      - name: "off-hours-restriction"
        condition: "action.risk_level == 'critical' AND time.business_hours == false"
        effect: "deny"
        exceptions: ["governance-admin", "on-call-security"]

# ============================================================================
# POLICY GOVERNANCE (META-GOVERNANCE)
# ============================================================================

policy_governance:
  # Policy Lifecycle Management
  lifecycle:
    states:
      - name: "draft"
        description: "Policy under development"
        allowed_actions: ["edit", "test", "submit"]
      
      - name: "review"
        description: "Policy pending approval"
        allowed_actions: ["approve", "reject", "comment"]
        required_approvers: 3
        approver_roles: ["governance-admin", "legal-counsel", "security-lead"]
      
      - name: "active"
        description: "Policy in enforcement"
        allowed_actions: ["enforce", "suspend", "retire"]
      
      - name: "suspended"
        description: "Policy temporarily disabled"
        allowed_actions: ["resume", "retire"]
      
      - name: "retired"
        description: "Policy no longer in use"
        allowed_actions: ["archive"]
    
    transitions:
      - from: "draft"
        to: "review"
        condition: "validation_passed AND impact_assessment_completed"
      
      - from: "review"
        to: "active"
        condition: "approved_by >= 3 AND legal_approved"
      
      - from: "active"
        to: "suspended"
        condition: "user.role == 'governance-admin' AND reason_provided"
  
  # Policy Validation Rules
  validation:
    - rule: "no_conflicting_policies"
      condition: "not has_conflicts(policy)"
      severity: "error"
      message: "Policy conflicts with existing policies"
    
    - rule: "valid_policy_syntax"
      condition: "is_valid_syntax(policy.rules)"
      severity: "error"
      message: "Policy contains syntax errors"
    
    - rule: "impact_assessment_required"
      condition: "policy.risk_level in ['high', 'critical'] implies has_impact_assessment(policy)"
      severity: "error"
      message: "High-risk policies require impact assessment"
    
    - rule: "policy_documentation"
      condition: "len(policy.description) >= 100"
      severity: "warning"
      message: "Policy should have detailed documentation"
  
  # Policy Approval Workflow
  approval:
    required_for:
      - "all policies"
      - "policy modifications"
      - "policy retirement"
    
    workflow:
      - stage: "technical_review"
        approvers: ["policy-manager", "senior-engineer"]
        minimum: 1
        timeout: 24h
      
      - stage: "security_review"
        approvers: ["security-lead", "security-architect"]
        minimum: 1
        timeout: 24h
      
      - stage: "legal_review"
        approvers: ["legal-counsel"]
        minimum: 1
        timeout: 48h
      
      - stage: "executive_approval"
        approvers: ["governance-admin", "ciso"]
        minimum: 1
        timeout: 48h
        required_for: ["critical policies"]
    
    escalation:
      - condition: "timeout_exceeded"
        action: "escalate_to_manager"
      
      - condition: "rejected_twice"
        action: "escalate_to_executive"

# ============================================================================
# ACCESS CONTROL POLICIES
# ============================================================================

access_control:
  # Token Management
  token_management:
    issuance:
      - token_type: "access_token"
        max_lifetime: 3600
        scopes_allowed: ["read", "write"]
        require_mfa: true
      
      - token_type: "service_token"
        max_lifetime: 86400
        scopes_allowed: ["read"]
        require_approval: true
    
    revocation:
      automatic:
        - condition: "user_disabled"
        - condition: "role_removed"
        - condition: "suspicious_activity"
      
      manual:
        required_role: "governance-admin"
        audit: true
  
  # Access Decision Caching
  caching:
    enabled: true
    ttl: 300  # 5 minutes
    invalidate_on:
      - "policy_updated"
      - "role_changed"
      - "user_disabled"

# ============================================================================
# AUDIT & COMPLIANCE
# ============================================================================

audit:
  # Audit Logging Requirements
  logging:
    enabled: true
    immutable: true
    
    events:
      - "policy_created"
      - "policy_updated"
      - "policy_deleted"
      - "policy_evaluated"
      - "access_granted"
      - "access_denied"
      - "token_issued"
      - "token_revoked"
      - "role_assigned"
      - "role_revoked"
      - "compliance_report_generated"
      - "violation_detected"
    
    retention:
      default: 365d
      critical_events: 2555d  # 7 years
      compliance_events: 2555d
    
    format:
      timestamp: true
      user_id: true
      action: true
      resource: true
      result: true
      ip_address: true
      user_agent: true
      request_id: true
      policy_id: true
      decision: true
      reason: true
  
  # Audit Trail Protection
  protection:
    encryption: true
    signing: true
    tamper_detection: true
    
    access_control:
      read: ["security-auditor", "compliance-officer"]
      export: ["security-auditor"]
      delete: []  # No deletion allowed

compliance:
  # Regulatory Frameworks
  frameworks:
    - name: "SOC2"
      enabled: true
      controls:
        - "CC6.1 - Logical and Physical Access Controls"
        - "CC6.2 - Prior to Issuing System Credentials"
        - "CC6.3 - Removes Access When Appropriate"
        - "CC7.2 - System Monitoring"
      
      reporting:
        frequency: "quarterly"
        recipients: ["compliance-officer@ninjatech.ai"]
    
    - name: "GDPR"
      enabled: true
      requirements:
        - "Article 5 - Principles relating to processing"
        - "Article 25 - Data protection by design"
        - "Article 30 - Records of processing activities"
        - "Article 32 - Security of processing"
      
      reporting:
        frequency: "monthly"
        recipients: ["dpo@ninjatech.ai"]
    
    - name: "ISO27001"
      enabled: true
      controls:
        - "A.9 - Access Control"
        - "A.12 - Operations Security"
        - "A.18 - Compliance"
  
  # Compliance Monitoring
  monitoring:
    - metric: "policy_violations"
      threshold: 0
      window: "1d"
      action: "alert"
      severity: "critical"
    
    - metric: "unauthorized_access_attempts"
      threshold: 10
      window: "1h"
      action: "alert"
      severity: "high"
    
    - metric: "audit_log_gaps"
      threshold: 0
      window: "1h"
      action: "alert"
      severity: "critical"
  
  # Compliance Reporting
  reporting:
    automated:
      - report_type: "access_review"
        frequency: "monthly"
        recipients: ["security-team@ninjatech.ai"]
      
      - report_type: "policy_effectiveness"
        frequency: "quarterly"
        recipients: ["governance-admin@ninjatech.ai"]
      
      - report_type: "compliance_status"
        frequency: "monthly"
        recipients: ["compliance-officer@ninjatech.ai"]

# ============================================================================
# SECURITY POLICIES
# ============================================================================

security:
  # Encryption
  encryption:
    at_rest:
      enabled: true
      algorithm: "AES-256-GCM"
      key_rotation: 30d  # Monthly rotation for governance
    
    in_transit:
      enabled: true
      protocol: "TLS 1.3"
      mutual_tls: true
  
  # Data Protection
  data_protection:
    pii_handling:
      detection: true
      masking: true
      encryption: true
      access_logging: true
    
    sensitive_data:
      - type: "policy_rules"
        classification: "confidential"
        encryption: true
      
      - type: "access_tokens"
        classification: "secret"
        encryption: true
        no_logging: true
  
  # Threat Protection
  threat_protection:
    rate_limiting:
      enabled: true
      rules:
        - scope: "user"
          limit: 100
          window: "1m"
        
        - scope: "ip"
          limit: 1000
          window: "1h"
    
    anomaly_detection:
      enabled: true
      alerts:
        - "unusual_access_patterns"
        - "privilege_escalation_attempts"
        - "policy_tampering"

# ============================================================================
# OPERATIONAL POLICIES
# ============================================================================

operational:
  # High Availability
  high_availability:
    replication: 3
    failover: "automatic"
    backup:
      frequency: "hourly"
      retention: 30d
  
  # Performance
  performance:
    - metric: "policy_evaluation_latency_p95"
      threshold: 100
      unit: "ms"
      action: "alert"
    
    - metric: "audit_log_write_latency_p99"
      threshold: 50
      unit: "ms"
      action: "alert"

# ============================================================================
# POLICY ENFORCEMENT
# ============================================================================

enforcement:
  mode: "strict"
  
  violations:
    - severity: "critical"
      action: "block_and_alert"
      notify: ["security-team@ninjatech.ai", "governance-admin@ninjatech.ai", "ciso@ninjatech.ai"]
      escalate: true
    
    - severity: "high"
      action: "block_and_alert"
      notify: ["security-team@ninjatech.ai"]
    
    - severity: "medium"
      action: "warn_and_log"
      notify: ["ops-team@ninjatech.ai"]
  
  updates:
    approval_required: true
    approvers: ["governance-admin", "security-lead", "legal-counsel"]
    minimum_approvals: 2
    
    rollback:
      enabled: true
      automatic: true
      retention: 10

# ============================================================================
# DOCUMENTATION
# ============================================================================

documentation:
  policy_guide: "https://docs.ninjatech.ai/mcp/governance-engine/policies"
  compliance_guide: "https://docs.ninjatech.ai/mcp/compliance"
  audit_guide: "https://docs.ninjatech.ai/mcp/audit"