# MCP Level 3 - Governance Engine Flow Definitions

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineFlow
metadata:
  name: governance-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Governance Engine workflow definitions"
  labels:
    engine-type: governance
    flow-type: orchestration

workflows:
  # Policy Evaluation Workflow
  - name: policy-evaluation
    description: "Evaluate access request against policies"
    type: sequential
    trigger:
      type: api
      endpoint: "/api/v1/governance/access/check"
      method: POST
    
    input:
      schema:
        type: object
        required: [subject, resource, action]
        properties:
          subject:
            type: object
          resource:
            type: object
          action:
            type: string
          context:
            type: object
    
    steps:
      - id: authenticate-subject
        name: "Authenticate Subject"
        type: service-call
        service: access-control-service
        action: authenticate
        input:
          subject: "{{workflow.input.subject}}"
        output:
          authenticated: "{{step.result.authenticated}}"
          user_id: "{{step.result.user_id}}"
        timeout: 2s
      
      - id: fetch-applicable-policies
        name: "Fetch Applicable Policies"
        type: service-call
        service: policy-engine
        action: get_policies
        input:
          resource_type: "{{workflow.input.resource.type}}"
          action: "{{workflow.input.action}}"
        output:
          policies: "{{step.result.policies}}"
        timeout: 1s
      
      - id: evaluate-policies
        name: "Evaluate Policies"
        type: service-call
        service: policy-engine
        action: evaluate
        input:
          policies: "{{steps.fetch-applicable-policies.output.policies}}"
          subject: "{{workflow.input.subject}}"
          resource: "{{workflow.input.resource}}"
          action: "{{workflow.input.action}}"
          context: "{{workflow.input.context}}"
        output:
          decision: "{{step.result.decision}}"
          matched_policies: "{{step.result.matched_policies}}"
        timeout: 500ms
      
      - id: log-decision
        name: "Log Access Decision"
        type: async
        service: audit-service
        action: log
        input:
          user_id: "{{steps.authenticate-subject.output.user_id}}"
          resource: "{{workflow.input.resource}}"
          action: "{{workflow.input.action}}"
          decision: "{{steps.evaluate-policies.output.decision}}"
          timestamp: "{{workflow.timestamp}}"
      
      - id: check-compliance
        name: "Check Compliance"
        type: conditional
        condition: "{{steps.evaluate-policies.output.decision == 'deny'}}"
        then:
          - type: service-call
            service: compliance-service
            action: check_violation
            input:
              decision: "{{steps.evaluate-policies.output.decision}}"
              policies: "{{steps.evaluate-policies.output.matched_policies}}"
    
    output:
      schema:
        type: object
        properties:
          allowed:
            type: boolean
          reason:
            type: string
          policies_evaluated:
            type: array

  # Policy Creation Workflow
  - name: policy-creation
    description: "Create and validate a new policy"
    type: sequential
    trigger:
      type: api
      endpoint: "/api/v1/governance/policies"
      method: POST
    
    input:
      schema:
        type: object
        required: [name, rules]
        properties:
          name:
            type: string
          rules:
            type: array
          enforcement:
            type: string
    
    steps:
      - id: validate-policy
        name: "Validate Policy"
        type: validation
        action: validate_policy_syntax
        input:
          name: "{{workflow.input.name}}"
          rules: "{{workflow.input.rules}}"
        output:
          validated_policy: "{{step.result.policy}}"
        timeout: 5s
      
      - id: check-conflicts
        name: "Check Policy Conflicts"
        type: service-call
        service: policy-engine
        action: check_conflicts
        input:
          policy: "{{steps.validate-policy.output.validated_policy}}"
        output:
          has_conflicts: "{{step.result.conflicts}}"
        timeout: 3s
      
      - id: request-approval
        name: "Request Approval"
        type: service-call
        service: approval-service
        action: request
        input:
          policy: "{{steps.validate-policy.output.validated_policy}}"
          approvers: ["governance-admin", "security-lead"]
        output:
          approval_id: "{{step.result.id}}"
        timeout: 5s
      
      - id: wait-for-approval
        name: "Wait for Approval"
        type: wait
        condition: "approval.status == 'approved'"
        timeout: 172800s  # 48 hours
      
      - id: store-policy
        name: "Store Policy"
        type: service-call
        service: policy-store
        action: create
        input:
          policy: "{{steps.validate-policy.output.validated_policy}}"
        output:
          policy_id: "{{step.result.id}}"
        timeout: 5s
      
      - id: activate-policy
        name: "Activate Policy"
        type: service-call
        service: policy-engine
        action: activate
        input:
          policy_id: "{{steps.store-policy.output.policy_id}}"
        timeout: 2s
    
    output:
      schema:
        type: object
        properties:
          policy_id:
            type: string
          status:
            type: string

  # Compliance Report Workflow
  - name: compliance-reporting
    description: "Generate compliance report"
    type: sequential
    trigger:
      type: schedule
      cron: "0 0 * * 0"  # Weekly
    
    input:
      schema:
        type: object
        required: [framework]
        properties:
          framework:
            type: string
            enum: [GDPR, SOC2, HIPAA]
          start_date:
            type: string
          end_date:
            type: string
    
    steps:
      - id: fetch-audit-logs
        name: "Fetch Audit Logs"
        type: service-call
        service: audit-service
        action: fetch
        input:
          start_date: "{{workflow.input.start_date}}"
          end_date: "{{workflow.input.end_date}}"
        output:
          audit_logs: "{{step.result.logs}}"
        timeout: 30s
      
      - id: analyze-compliance
        name: "Analyze Compliance"
        type: service-call
        service: compliance-service
        action: analyze
        input:
          framework: "{{workflow.input.framework}}"
          audit_logs: "{{steps.fetch-audit-logs.output.audit_logs}}"
        output:
          findings: "{{step.result.findings}}"
          score: "{{step.result.score}}"
        timeout: 60s
      
      - id: generate-report
        name: "Generate Report"
        type: service-call
        service: compliance-service
        action: generate_report
        input:
          framework: "{{workflow.input.framework}}"
          findings: "{{steps.analyze-compliance.output.findings}}"
          score: "{{steps.analyze-compliance.output.score}}"
        output:
          report_id: "{{step.result.id}}"
          report_url: "{{step.result.url}}"
        timeout: 30s
      
      - id: notify-stakeholders
        name: "Notify Stakeholders"
        type: notification
        action: send
        input:
          recipients: ["compliance-officer@ninjatech.ai"]
          subject: "Compliance Report - {{workflow.input.framework}}"
          body: "Report available at: {{steps.generate-report.output.report_url}}"
    
    output:
      schema:
        type: object
        properties:
          report_id:
            type: string
          report_url:
            type: string

error_handling:
  patterns:
    - name: policy-evaluation-retry
      max_retries: 2
      backoff: linear

state_management:
  storage: redis
  ttl: 3600

monitoring:
  metrics:
    - name: policy_evaluation_duration
      type: histogram
    - name: access_denied_total
      type: counter

documentation:
  workflow_guide: "https://docs.ninjatech.ai/mcp/governance-engine/workflows"
