# MCP Level 3 - DAG Engine Bundle
# Defines component inventory, deployment configuration, and resource management

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineBundle
metadata:
  name: dag-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "DAG Engine deployment bundle with all components and configurations"
  labels:
    engine-type: dag
    deployment-tier: core
    criticality: critical
  annotations:
    mcp.ninjatech.ai/bundle-version: "1.0.0"
    mcp.ninjatech.ai/last-updated: "2024-01-11"

# ============================================================================
# COMPONENT INVENTORY
# ============================================================================

components:
  services:
    - name: dag-api-service
      type: rest-api
      version: 1.0.0
      description: "REST API service for DAG operations"
      image: "ninjatech/dag-api:1.0.0"
      port: 8080
      replicas: 3
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
    
    - name: dag-scheduler
      type: scheduler
      version: 1.0.0
      description: "DAG scheduling and orchestration service"
      image: "ninjatech/dag-scheduler:1.0.0"
      port: 8081
      replicas: 3
      resources:
        requests:
          cpu: "1000m"
          memory: "2Gi"
        limits:
          cpu: "4000m"
          memory: "8Gi"
    
    - name: dag-executor
      type: executor
      version: 1.0.0
      description: "Task execution service"
      image: "ninjatech/dag-executor:1.0.0"
      port: 8082
      replicas: 10
      resources:
        requests:
          cpu: "2000m"
          memory: "4Gi"
        limits:
          cpu: "8000m"
          memory: "16Gi"
    
    - name: dag-monitor
      type: monitoring
      version: 1.0.0
      description: "DAG execution monitoring service"
      image: "ninjatech/dag-monitor:1.0.0"
      port: 8083
      replicas: 2
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
    
    - name: lineage-tracker
      type: service
      version: 1.0.0
      description: "Data lineage tracking service"
      image: "ninjatech/lineage-tracker:1.0.0"
      port: 8084
      replicas: 2
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
  
  datastores:
    - name: metadata-store
      type: relational-db
      provider: "postgresql"
      version: "15.x"
      configuration:
        replicas: 3
        max_connections: 2000
      resources:
        storage: "500Gi"
        memory: "32Gi"
    
    - name: state-store
      type: key-value
      provider: "redis"
      version: "7.x"
      configuration:
        replicas: 3
        cluster_mode: true
      resources:
        memory: "16Gi"
    
    - name: log-store
      type: object-storage
      provider: "s3"
      configuration:
        bucket: "dag-logs"
        retention: 90d
      resources:
        storage: "10Ti"
  
  libraries:
    - name: dag-client-sdk
      type: sdk
      language: python
      version: 1.0.0
      repository: "https://github.com/ninjatech/dag-client-sdk"
  
  integrations:
    - name: message-queue
      type: messaging
      provider: "kafka"
      endpoint: "kafka.ninjatech.ai:9092"

deployment:
  strategy:
    type: "rolling"
    rolling_update:
      max_surge: 1
      max_unavailable: 0
  
  scaling:
    horizontal:
      enabled: true
      min_replicas: 3
      max_replicas: 50
      metrics:
        - type: cpu
          target: 70
        - type: custom
          name: dag_runs_queued
          target: 100
  
  quotas:
    cpu: "200"
    memory: "400Gi"
    storage: "15Ti"

environments:
  production:
    replicas: 3
    resources:
      cpu: "200"
      memory: "400Gi"
    features:
      high_availability: true
      auto_scaling: true

secrets:
  - name: metadata-db-credentials
    type: credentials
    provider: vault
    path: "secret/dag/metadata-db"
  
  - name: kafka-credentials
    type: credentials
    provider: vault
    path: "secret/dag/kafka"

health_checks:
  liveness:
    http_get:
      path: "/health/live"
      port: 8080
    initial_delay: 30s
    period: 10s
  
  readiness:
    http_get:
      path: "/health/ready"
      port: 8080
    initial_delay: 10s
    period: 5s

observability:
  metrics:
    enabled: true
    provider: prometheus
    custom_metrics:
      - name: dag_runs_total
        type: counter
      - name: dag_execution_duration
        type: histogram
      - name: task_failures_total
        type: counter
  
  logging:
    enabled: true
    provider: elasticsearch
    level: info
  
  tracing:
    enabled: true
    provider: jaeger
    sampling_rate: 0.1

security:
  pod_security:
    run_as_non_root: true
    run_as_user: 1000
  
  network_policies:
    - name: allow-ingress
      ingress:
        - from:
            - namespace_selector:
                match_labels:
                  name: ingress-nginx

backup:
  enabled: true
  schedule: "0 2 * * *"
  retention: 30d
  targets:
    - metadata-store
    - state-store

documentation:
  deployment_guide: "https://docs.ninjatech.ai/mcp/dag-engine/deployment"
  operations_manual: "https://docs.ninjatech.ai/mcp/dag-engine/operations"