# MCP Level 3 - DAG Engine Specification
# Defines API specifications, interface contracts, and integration patterns

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineSpec
metadata:
  name: dag-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Directed Acyclic Graph Engine API Specification"
  labels:
    engine-type: dag
    capability: workflow-orchestration
    tier: core
  annotations:
    mcp.ninjatech.ai/spec-version: "1.0.0"
    mcp.ninjatech.ai/last-updated: "2024-01-15"

# ============================================================================
# API SPECIFICATIONS
# ============================================================================

api:
  # REST API Specification
  rest:
    baseUrl: "/api/v1/dag"
    version: "1.0.0"
    
    endpoints:
      # DAG Definition Endpoints
      - path: "/dags"
        method: POST
        operationId: createDAG
        summary: "Create a new DAG definition"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [name, tasks]
                properties:
                  name:
                    type: string
                    pattern: "^[a-z0-9-]+$"
                  description:
                    type: string
                  tasks:
                    type: array
                    items:
                      $ref: "#/components/schemas/TaskDefinition"
                  schedule:
                    type: object
                    properties:
                      cron:
                        type: string
                      timezone:
                        type: string
                  default_args:
                    type: object
        responses:
          201:
            description: "DAG created successfully"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/DAGResponse"
          400:
            $ref: "#/components/responses/BadRequest"
      
      - path: "/dags"
        method: GET
        operationId: listDAGs
        summary: "List all DAG definitions"
        parameters:
          - name: status
            in: query
            schema:
              type: string
              enum: [active, paused, archived]
          - name: tags
            in: query
            schema:
              type: array
              items:
                type: string
        responses:
          200:
            description: "List of DAGs"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/DAGSummary"
      
      - path: "/dags/{dag_id}"
        method: GET
        operationId: getDAG
        summary: "Get DAG definition by ID"
        parameters:
          - name: dag_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "DAG definition"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/DAGResponse"
      
      - path: "/dags/{dag_id}"
        method: PUT
        operationId: updateDAG
        summary: "Update DAG definition"
        parameters:
          - name: dag_id
            in: path
            required: true
            schema:
              type: string
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DAGUpdate"
        responses:
          200:
            description: "DAG updated"
      
      - path: "/dags/{dag_id}"
        method: DELETE
        operationId: deleteDAG
        summary: "Delete DAG definition"
        parameters:
          - name: dag_id
            in: path
            required: true
            schema:
              type: string
        responses:
          204:
            description: "DAG deleted"
      
      # DAG Execution Endpoints
      - path: "/dags/{dag_id}/runs"
        method: POST
        operationId: triggerDAGRun
        summary: "Trigger a DAG execution"
        parameters:
          - name: dag_id
            in: path
            required: true
            schema:
              type: string
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  conf:
                    type: object
                  execution_date:
                    type: string
                    format: date-time
        responses:
          201:
            description: "DAG run triggered"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/DAGRunResponse"
      
      - path: "/dags/{dag_id}/runs"
        method: GET
        operationId: listDAGRuns
        summary: "List DAG execution runs"
        parameters:
          - name: dag_id
            in: path
            required: true
            schema:
              type: string
          - name: state
            in: query
            schema:
              type: string
              enum: [queued, running, success, failed]
          - name: limit
            in: query
            schema:
              type: integer
              default: 100
        responses:
          200:
            description: "List of DAG runs"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/DAGRunSummary"
      
      - path: "/dags/{dag_id}/runs/{run_id}"
        method: GET
        operationId: getDAGRun
        summary: "Get DAG run details"
        parameters:
          - name: dag_id
            in: path
            required: true
            schema:
              type: string
          - name: run_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "DAG run details"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/DAGRunResponse"
      
      - path: "/dags/{dag_id}/runs/{run_id}/cancel"
        method: POST
        operationId: cancelDAGRun
        summary: "Cancel a running DAG"
        parameters:
          - name: dag_id
            in: path
            required: true
            schema:
              type: string
          - name: run_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "DAG run cancelled"
      
      # Task Instance Endpoints
      - path: "/dags/{dag_id}/runs/{run_id}/tasks/{task_id}"
        method: GET
        operationId: getTaskInstance
        summary: "Get task instance details"
        parameters:
          - name: dag_id
            in: path
            required: true
            schema:
              type: string
          - name: run_id
            in: path
            required: true
            schema:
              type: string
          - name: task_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Task instance details"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/TaskInstance"
      
      - path: "/dags/{dag_id}/runs/{run_id}/tasks/{task_id}/retry"
        method: POST
        operationId: retryTask
        summary: "Retry a failed task"
        parameters:
          - name: dag_id
            in: path
            required: true
            schema:
              type: string
          - name: run_id
            in: path
            required: true
            schema:
              type: string
          - name: task_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Task retry initiated"
      
      # Dependency Analysis Endpoints
      - path: "/dags/{dag_id}/dependencies"
        method: GET
        operationId: getDAGDependencies
        summary: "Get DAG dependency graph"
        parameters:
          - name: dag_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Dependency graph"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/DependencyGraph"
      
      - path: "/dags/{dag_id}/critical-path"
        method: GET
        operationId: getCriticalPath
        summary: "Get critical path analysis"
        parameters:
          - name: dag_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Critical path"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/CriticalPath"
      
      # Lineage Endpoints
      - path: "/lineage/data/{dataset_id}"
        method: GET
        operationId: getDataLineage
        summary: "Get data lineage for a dataset"
        parameters:
          - name: dataset_id
            in: path
            required: true
            schema:
              type: string
          - name: direction
            in: query
            schema:
              type: string
              enum: [upstream, downstream, both]
              default: both
          - name: depth
            in: query
            schema:
              type: integer
              default: 3
        responses:
          200:
            description: "Data lineage graph"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/LineageGraph"
      
      # Metrics Endpoints
      - path: "/metrics/dags/{dag_id}"
        method: GET
        operationId: getDAGMetrics
        summary: "Get DAG execution metrics"
        parameters:
          - name: dag_id
            in: path
            required: true
            schema:
              type: string
          - name: start_date
            in: query
            schema:
              type: string
              format: date-time
          - name: end_date
            in: query
            schema:
              type: string
              format: date-time
        responses:
          200:
            description: "DAG metrics"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/DAGMetrics"
  
  # gRPC API Specification
  grpc:
    package: "mcp.dag.v1"
    services:
      - name: DAGService
        methods:
          - name: CreateDAG
            input: CreateDAGRequest
            output: DAGResponse
            streaming: false
          
          - name: TriggerDAGRun
            input: TriggerDAGRunRequest
            output: DAGRunResponse
            streaming: false
          
          - name: StreamDAGRun
            input: StreamDAGRunRequest
            output: stream DAGRunEvent
            streaming: true
          
          - name: GetDependencies
            input: GetDependenciesRequest
            output: DependencyGraph
            streaming: false
          
          - name: GetLineage
            input: GetLineageRequest
            output: LineageGraph
            streaming: false
  
  # Event Streaming Specification
  events:
    protocol: kafka
    topics:
      - name: dag.created
        schema: DAGCreatedEvent
        partitions: 5
        retention: 30d
      
      - name: dag.run.started
        schema: DAGRunStartedEvent
        partitions: 10
        retention: 7d
      
      - name: dag.run.completed
        schema: DAGRunCompletedEvent
        partitions: 10
        retention: 30d
      
      - name: dag.task.started
        schema: TaskStartedEvent
        partitions: 20
        retention: 7d
      
      - name: dag.task.completed
        schema: TaskCompletedEvent
        partitions: 20
        retention: 7d
      
      - name: dag.task.failed
        schema: TaskFailedEvent
        partitions: 10
        retention: 30d

# ============================================================================
# DATA SCHEMAS
# ============================================================================

components:
  schemas:
    TaskDefinition:
      type: object
      required: [task_id, operator]
      properties:
        task_id:
          type: string
        operator:
          type: string
        dependencies:
          type: array
          items:
            type: string
        params:
          type: object
        retries:
          type: integer
          default: 3
        retry_delay:
          type: integer
          default: 300
        timeout:
          type: integer
    
    DAGResponse:
      type: object
      properties:
        dag_id:
          type: string
        name:
          type: string
        description:
          type: string
        tasks:
          type: array
          items:
            $ref: "#/components/schemas/TaskDefinition"
        schedule:
          type: object
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    
    DAGSummary:
      type: object
      properties:
        dag_id:
          type: string
        name:
          type: string
        status:
          type: string
        last_run:
          type: string
          format: date-time
        next_run:
          type: string
          format: date-time
    
    DAGRunResponse:
      type: object
      properties:
        run_id:
          type: string
        dag_id:
          type: string
        state:
          type: string
          enum: [queued, running, success, failed]
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        duration:
          type: number
        task_instances:
          type: array
          items:
            $ref: "#/components/schemas/TaskInstance"
    
    TaskInstance:
      type: object
      properties:
        task_id:
          type: string
        state:
          type: string
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        duration:
          type: number
        try_number:
          type: integer
        log_url:
          type: string
    
    DependencyGraph:
      type: object
      properties:
        nodes:
          type: array
          items:
            type: object
        edges:
          type: array
          items:
            type: object
        adjacency_matrix:
          type: array
          items:
            type: array
            items:
              type: integer
    
    CriticalPath:
      type: object
      properties:
        path:
          type: array
          items:
            type: string
        total_duration:
          type: number
        bottlenecks:
          type: array
          items:
            type: object
    
    LineageGraph:
      type: object
      properties:
        dataset_id:
          type: string
        upstream:
          type: array
        downstream:
          type: array
        transformations:
          type: array
    
    DAGMetrics:
      type: object
      properties:
        total_runs:
          type: integer
        success_rate:
          type: number
        avg_duration:
          type: number
        failure_rate:
          type: number
  
  responses:
    BadRequest:
      description: "Invalid request"
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

# ============================================================================
# INTERFACE CONTRACTS
# ============================================================================

contracts:
  sla:
    availability: 99.95%
    latency:
      p50: 100ms
      p95: 300ms
      p99: 500ms
    throughput:
      dag_runs_per_second: 100
  
  quality:
    execution:
      max_retry_attempts: 3
      timeout: 3600s
    
    reliability:
      min_success_rate: 0.95

# ============================================================================
# INTEGRATION PATTERNS
# ============================================================================

integration:
  upstream:
    - service: scheduler
      protocol: grpc
    - service: executor
      protocol: grpc
    - service: metadata-store
      protocol: postgresql
  
  downstream:
    - service: monitoring
      protocol: kafka
    - service: alerting
      protocol: rest

# ============================================================================
# VERSIONING & COMPATIBILITY
# ============================================================================

versioning:
  strategy: semantic
  current: 1.0.0
  supported: [1.0.0]
  compatibility:
    backward: true
    forward: false

# ============================================================================
# DOCUMENTATION
# ============================================================================

documentation:
  openapi: "https://docs.ninjatech.ai/mcp/dag-engine/openapi.yaml"
  examples: "https://github.com/ninjatech/mcp-examples/dag"