# MCP Level 3 - DAG Engine Flow Definitions

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineFlow
metadata:
  name: dag-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "DAG Engine workflow definitions and orchestration patterns"
  labels:
    engine-type: dag
    flow-type: orchestration

# ============================================================================
# WORKFLOW DEFINITIONS
# ============================================================================

workflows:
  # DAG Execution Workflow
  - name: dag-execution
    description: "Execute a DAG with all its tasks"
    type: sequential
    trigger:
      type: api
      endpoint: "/api/v1/dag/{dag_id}/runs"
      method: POST
    
    input:
      schema:
        type: object
        required: [dag_id]
        properties:
          dag_id:
            type: string
          execution_date:
            type: string
            format: date-time
          conf:
            type: object
    
    steps:
      - id: validate-dag
        name: "Validate DAG"
        type: validation
        action: validate_dag_definition
        input:
          dag_id: "{{workflow.input.dag_id}}"
        output:
          dag_definition: "{{step.result.definition}}"
        timeout: 5s
      
      - id: create-execution-plan
        name: "Create Execution Plan"
        type: service-call
        service: dag-scheduler
        action: create_plan
        input:
          dag_definition: "{{steps.validate-dag.output.dag_definition}}"
          execution_date: "{{workflow.input.execution_date}}"
        output:
          execution_plan: "{{step.result.plan}}"
          task_order: "{{step.result.task_order}}"
        timeout: 10s
      
      - id: initialize-state
        name: "Initialize Execution State"
        type: service-call
        service: state-store
        action: initialize
        input:
          dag_id: "{{workflow.input.dag_id}}"
          execution_plan: "{{steps.create-execution-plan.output.execution_plan}}"
        output:
          execution_id: "{{step.result.execution_id}}"
        timeout: 5s
      
      - id: execute-tasks
        name: "Execute Tasks"
        type: loop
        iterator: "{{steps.create-execution-plan.output.task_order}}"
        steps:
          - id: check-dependencies
            name: "Check Task Dependencies"
            type: service-call
            service: dag-scheduler
            action: check_dependencies
            input:
              task_id: "{{loop.item}}"
              execution_id: "{{steps.initialize-state.output.execution_id}}"
            output:
              dependencies_met: "{{step.result.met}}"
          
          - id: execute-task
            name: "Execute Task"
            type: conditional
            condition: "{{steps.check-dependencies.output.dependencies_met}}"
            then:
              - type: service-call
                service: dag-executor
                action: execute
                input:
                  task_id: "{{loop.item}}"
                  execution_id: "{{steps.initialize-state.output.execution_id}}"
                  conf: "{{workflow.input.conf}}"
                output:
                  task_result: "{{step.result}}"
                error_handling:
                  on_error: retry
                  max_retries: 3
                timeout: 3600s
          
          - id: update-state
            name: "Update Task State"
            type: service-call
            service: state-store
            action: update_task_state
            input:
              execution_id: "{{steps.initialize-state.output.execution_id}}"
              task_id: "{{loop.item}}"
              status: "{{steps.execute-task.output.task_result.status}}"
            timeout: 5s
      
      - id: finalize-execution
        name: "Finalize Execution"
        type: service-call
        service: dag-scheduler
        action: finalize
        input:
          execution_id: "{{steps.initialize-state.output.execution_id}}"
        output:
          final_status: "{{step.result.status}}"
        timeout: 10s
      
      - id: track-lineage
        name: "Track Data Lineage"
        type: async
        service: lineage-tracker
        action: track
        input:
          execution_id: "{{steps.initialize-state.output.execution_id}}"
          dag_id: "{{workflow.input.dag_id}}"
      
      - id: publish-completion
        name: "Publish Completion Event"
        type: event
        action: publish
        target:
          type: kafka
          topic: dag.run.completed
        payload:
          execution_id: "{{steps.initialize-state.output.execution_id}}"
          dag_id: "{{workflow.input.dag_id}}"
          status: "{{steps.finalize-execution.output.final_status}}"
          duration: "{{workflow.duration}}"
    
    output:
      schema:
        type: object
        properties:
          execution_id:
            type: string
          status:
            type: string
          duration:
            type: number
    
    error_handling:
      global:
        on_error: rollback
        notify: ["dag-ops@ninjatech.ai"]

  # DAG Creation Workflow
  - name: dag-creation
    description: "Create and validate a new DAG"
    type: sequential
    trigger:
      type: api
      endpoint: "/api/v1/dags"
      method: POST
    
    input:
      schema:
        type: object
        required: [name, tasks]
        properties:
          name:
            type: string
          tasks:
            type: array
          schedule:
            type: object
    
    steps:
      - id: validate-dag-structure
        name: "Validate DAG Structure"
        type: validation
        action: validate_dag_structure
        input:
          name: "{{workflow.input.name}}"
          tasks: "{{workflow.input.tasks}}"
        output:
          validated_dag: "{{step.result.dag}}"
        timeout: 10s
      
      - id: check-cycles
        name: "Check for Cycles"
        type: service-call
        service: dag-validator
        action: check_cycles
        input:
          tasks: "{{workflow.input.tasks}}"
        output:
          is_acyclic: "{{step.result.acyclic}}"
        timeout: 5s
      
      - id: store-dag-definition
        name: "Store DAG Definition"
        type: service-call
        service: metadata-store
        action: create_dag
        input:
          dag: "{{steps.validate-dag-structure.output.validated_dag}}"
          schedule: "{{workflow.input.schedule}}"
        output:
          dag_id: "{{step.result.id}}"
        timeout: 10s
      
      - id: register-schedule
        name: "Register Schedule"
        type: conditional
        condition: "{{workflow.input.schedule != null}}"
        then:
          - type: service-call
            service: dag-scheduler
            action: register_schedule
            input:
              dag_id: "{{steps.store-dag-definition.output.dag_id}}"
              schedule: "{{workflow.input.schedule}}"
        timeout: 5s
    
    output:
      schema:
        type: object
        properties:
          dag_id:
            type: string
          status:
            type: string

  # Dependency Analysis Workflow
  - name: dependency-analysis
    description: "Analyze DAG dependencies and critical path"
    type: sequential
    trigger:
      type: api
      endpoint: "/api/v1/dags/{dag_id}/dependencies"
      method: GET
    
    input:
      schema:
        type: object
        required: [dag_id]
        properties:
          dag_id:
            type: string
    
    steps:
      - id: fetch-dag
        name: "Fetch DAG Definition"
        type: service-call
        service: metadata-store
        action: get_dag
        input:
          dag_id: "{{workflow.input.dag_id}}"
        output:
          dag_definition: "{{step.result.definition}}"
        timeout: 5s
      
      - id: build-dependency-graph
        name: "Build Dependency Graph"
        type: service-call
        service: dag-analyzer
        action: build_graph
        input:
          dag_definition: "{{steps.fetch-dag.output.dag_definition}}"
        output:
          dependency_graph: "{{step.result.graph}}"
        timeout: 10s
      
      - id: compute-critical-path
        name: "Compute Critical Path"
        type: service-call
        service: dag-analyzer
        action: critical_path
        input:
          dependency_graph: "{{steps.build-dependency-graph.output.dependency_graph}}"
        output:
          critical_path: "{{step.result.path}}"
          total_duration: "{{step.result.duration}}"
        timeout: 5s
      
      - id: identify-bottlenecks
        name: "Identify Bottlenecks"
        type: service-call
        service: dag-analyzer
        action: find_bottlenecks
        input:
          dependency_graph: "{{steps.build-dependency-graph.output.dependency_graph}}"
        output:
          bottlenecks: "{{step.result.bottlenecks}}"
        timeout: 5s
    
    output:
      schema:
        type: object
        properties:
          dependency_graph:
            type: object
          critical_path:
            type: array
          bottlenecks:
            type: array

# ============================================================================
# ERROR HANDLING PATTERNS
# ============================================================================

error_handling:
  patterns:
    - name: task-retry
      strategy: exponential
      max_retries: 3
      initial_delay: 60s
    
    - name: dag-rollback
      on_failure: rollback_completed_tasks
      notify: true

# ============================================================================
# STATE MANAGEMENT
# ============================================================================

state_management:
  storage: redis
  ttl: 86400
  persistence: true

# ============================================================================
# MONITORING
# ============================================================================

monitoring:
  metrics:
    - name: dag_execution_duration
      type: histogram
    - name: task_execution_duration
      type: histogram
    - name: dag_failure_rate
      type: counter
  
  tracing:
    enabled: true
    provider: jaeger

documentation:
  workflow_guide: "https://docs.ninjatech.ai/mcp/dag-engine/workflows"
