# MCP Level 3 - Promotion Engine Dependency Graph

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineGraph
metadata:
  name: promotion-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Promotion Engine dependency graph"
  labels:
    engine-type: promotion
    graph-type: dependency

nodes:
  - id: promotion-api-service
    type: service
    category: api
    name: "Promotion API Service"
    properties:
      port: 8080
      replicas: 3
      criticality: high
  
  - id: promotion-orchestrator
    type: service
    category: core
    name: "Promotion Orchestrator"
    properties:
      port: 8081
      replicas: 3
      criticality: critical
  
  - id: deployment-service
    type: service
    category: core
    name: "Deployment Service"
    properties:
      port: 8082
      replicas: 5
      criticality: critical
  
  - id: approval-service
    type: service
    category: core
    name: "Approval Service"
    properties:
      port: 8083
      replicas: 2
      criticality: high
  
  - id: health-monitor
    type: service
    category: monitoring
    name: "Health Monitor"
    properties:
      port: 8084
      replicas: 3
      criticality: high
  
  - id: promotion-store
    type: datastore
    category: storage
    name: "Promotion Store"
    properties:
      provider: postgresql
      criticality: critical
  
  - id: deployment-history
    type: datastore
    category: storage
    name: "Deployment History"
    properties:
      provider: timescaledb
      criticality: high
  
  - id: kubernetes-api
    type: external
    category: orchestration
    name: "Kubernetes API"
    properties:
      provider: kubernetes
      criticality: critical
  
  - id: artifact-registry
    type: external
    category: registry
    name: "Artifact Registry"
    properties:
      provider: harbor
      criticality: critical

edges:
  - source: promotion-api-service
    target: promotion-orchestrator
    type: synchronous
    protocol: grpc
    properties:
      latency: 30ms
      throughput: 500rps
  
  - source: promotion-orchestrator
    target: approval-service
    type: synchronous
    protocol: http
    properties:
      latency: 50ms
      throughput: 200rps
  
  - source: promotion-orchestrator
    target: deployment-service
    type: asynchronous
    protocol: kafka
    properties:
      topic: "promotion.deployments"
  
  - source: deployment-service
    target: kubernetes-api
    type: synchronous
    protocol: https
    properties:
      latency: 100ms
      throughput: 100rps
  
  - source: deployment-service
    target: artifact-registry
    type: synchronous
    protocol: https
    properties:
      latency: 200ms
      throughput: 100rps
  
  - source: deployment-service
    target: deployment-history
    type: asynchronous
    protocol: postgresql
    properties:
      latency: 50ms
  
  - source: health-monitor
    target: kubernetes-api
    type: synchronous
    protocol: https
    properties:
      latency: 50ms
      throughput: 1000rps
  
  - source: approval-service
    target: promotion-store
    type: synchronous
    protocol: postgresql
    properties:
      latency: 30ms
      throughput: 500rps

dependency_matrix:
  services:
    - promotion-api-service
    - promotion-orchestrator
    - deployment-service
    - approval-service
    - health-monitor
  
  matrix:
    promotion-api-service: [0, 1, 0, 0, 0]
    promotion-orchestrator: [0, 0, 1, 1, 0]
    deployment-service: [0, 0, 0, 0, 0]
    approval-service: [0, 0, 0, 0, 0]
    health-monitor: [0, 0, 0, 0, 0]

data_flows:
  - name: promotion-flow
    steps:
      - step: 1
        component: promotion-api-service
        action: "Receive promotion request"
      - step: 2
        component: approval-service
        action: "Request approval"
      - step: 3
        component: deployment-service
        action: "Deploy artifact"
      - step: 4
        component: health-monitor
        action: "Monitor health"

critical_paths:
  - name: promotion-critical-path
    path:
      - promotion-api-service
      - promotion-orchestrator
      - deployment-service
      - kubernetes-api
    total_latency: 180ms

performance:
  throughput:
    promotions_per_hour: 100
  latency:
    p50: 200ms
    p95: 500ms
    p99: 1000ms

documentation:
  architecture_diagram: "https://docs.ninjatech.ai/mcp/promotion-engine/architecture"
