# MCP Level 3 - Promotion Engine Specification
# Defines API specifications, interface contracts, and integration patterns

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineSpec
metadata:
  name: promotion-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Promotion Engine API Specification"
  labels:
    engine-type: promotion
    capability: deployment-management
    tier: core
  annotations:
    mcp.ninjatech.ai/spec-version: "1.0.0"
    mcp.ninjatech.ai/last-updated: "2024-01-15"

# ============================================================================
# API SPECIFICATIONS
# ============================================================================

api:
  rest:
    baseUrl: "/api/v1/promotion"
    version: "1.0.0"
    
    endpoints:
      # Promotion Plan Management
      - path: "/plans"
        method: POST
        operationId: createPromotionPlan
        summary: "Create a promotion plan"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [name, artifact_id, source_env, target_env]
                properties:
                  name:
                    type: string
                  artifact_id:
                    type: string
                  source_env:
                    type: string
                  target_env:
                    type: string
                  strategy:
                    type: string
                    enum: [blue_green, canary, rolling, recreate]
                  approval_required:
                    type: boolean
        responses:
          201:
            description: "Promotion plan created"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/PromotionPlanResponse"
      
      - path: "/plans/{plan_id}"
        method: GET
        operationId: getPromotionPlan
        summary: "Get promotion plan"
        parameters:
          - name: plan_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Promotion plan details"
      
      - path: "/plans/{plan_id}/execute"
        method: POST
        operationId: executePromotion
        summary: "Execute a promotion"
        parameters:
          - name: plan_id
            in: path
            required: true
            schema:
              type: string
        responses:
          202:
            description: "Promotion started"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/PromotionResponse"
      
      # Approval Management
      - path: "/approvals"
        method: POST
        operationId: requestApproval
        summary: "Request promotion approval"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [promotion_id, approvers]
                properties:
                  promotion_id:
                    type: string
                  approvers:
                    type: array
                    items:
                      type: string
                  deadline:
                    type: string
                    format: date-time
        responses:
          201:
            description: "Approval requested"
      
      - path: "/approvals/{approval_id}/approve"
        method: POST
        operationId: approvePromotion
        summary: "Approve a promotion"
        parameters:
          - name: approval_id
            in: path
            required: true
            schema:
              type: string
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment:
                    type: string
        responses:
          200:
            description: "Promotion approved"
      
      - path: "/approvals/{approval_id}/reject"
        method: POST
        operationId: rejectPromotion
        summary: "Reject a promotion"
        parameters:
          - name: approval_id
            in: path
            required: true
            schema:
              type: string
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [reason]
                properties:
                  reason:
                    type: string
        responses:
          200:
            description: "Promotion rejected"
      
      # Deployment Management
      - path: "/deployments"
        method: POST
        operationId: createDeployment
        summary: "Create a deployment"
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [artifact_id, environment, manifest]
                properties:
                  artifact_id:
                    type: string
                  environment:
                    type: string
                  manifest:
                    type: object
                  strategy:
                    type: string
        responses:
          201:
            description: "Deployment created"
      
      - path: "/deployments/{deployment_id}"
        method: GET
        operationId: getDeployment
        summary: "Get deployment status"
        parameters:
          - name: deployment_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Deployment details"
      
      - path: "/deployments/{deployment_id}/rollback"
        method: POST
        operationId: rollbackDeployment
        summary: "Rollback a deployment"
        parameters:
          - name: deployment_id
            in: path
            required: true
            schema:
              type: string
        responses:
          202:
            description: "Rollback initiated"
      
      # Health Monitoring
      - path: "/deployments/{deployment_id}/health"
        method: GET
        operationId: getDeploymentHealth
        summary: "Get deployment health status"
        parameters:
          - name: deployment_id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: "Health status"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/HealthStatus"
      
      # Promoted Artifacts
      - path: "/artifacts/promoted"
        method: GET
        operationId: listPromotedArtifacts
        summary: "List promoted artifacts"
        parameters:
          - name: environment
            in: query
            schema:
              type: string
          - name: status
            in: query
            schema:
              type: string
        responses:
          200:
            description: "List of promoted artifacts"
  
  grpc:
    package: "mcp.promotion.v1"
    services:
      - name: PromotionService
        methods:
          - name: ExecutePromotion
            input: ExecutePromotionRequest
            output: PromotionResponse
          
          - name: StreamDeployment
            input: StreamDeploymentRequest
            output: stream DeploymentEvent
          
          - name: ManageApproval
            input: ApprovalRequest
            output: ApprovalResponse
  
  events:
    protocol: kafka
    topics:
      - name: promotion.started
        schema: PromotionStartedEvent
        partitions: 5
        retention: 30d
      
      - name: promotion.completed
        schema: PromotionCompletedEvent
        partitions: 5
        retention: 30d
      
      - name: promotion.failed
        schema: PromotionFailedEvent
        partitions: 5
        retention: 30d
      
      - name: deployment.created
        schema: DeploymentCreatedEvent
        partitions: 10
        retention: 30d
      
      - name: approval.requested
        schema: ApprovalRequestedEvent
        partitions: 5
        retention: 30d

# ============================================================================
# DATA SCHEMAS
# ============================================================================

components:
  schemas:
    PromotionPlanResponse:
      type: object
      properties:
        plan_id:
          type: string
        name:
          type: string
        artifact_id:
          type: string
        source_env:
          type: string
        target_env:
          type: string
        strategy:
          type: string
        created_at:
          type: string
          format: date-time
    
    PromotionResponse:
      type: object
      properties:
        promotion_id:
          type: string
        plan_id:
          type: string
        status:
          type: string
          enum: [pending, in_progress, completed, failed, rolled_back]
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
    
    HealthStatus:
      type: object
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
        checks:
          type: array
        last_check:
          type: string
          format: date-time

contracts:
  sla:
    availability: 99.95%
    latency:
      p50: 200ms
      p95: 500ms
      p99: 1000ms

integration:
  upstream:
    - service: artifact-registry
      protocol: rest
    - service: deployment-platform
      protocol: kubernetes
  
  downstream:
    - service: monitoring
      protocol: prometheus
    - service: notification
      protocol: rest

versioning:
  strategy: semantic
  current: 1.0.0
  supported: [1.0.0]

documentation:
  openapi: "https://docs.ninjatech.ai/mcp/promotion-engine/openapi.yaml"