# MCP Level 3 - Promotion Engine Flow Definitions

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EngineFlow
metadata:
  name: promotion-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Promotion Engine workflow definitions"
  labels:
    engine-type: promotion
    flow-type: orchestration

workflows:
  # Artifact Promotion Workflow
  - name: artifact-promotion
    description: "Promote artifact through environments"
    type: sequential
    trigger:
      type: api
      endpoint: "/api/v1/promotion/plans/{plan_id}/execute"
      method: POST
    
    input:
      schema:
        type: object
        required: [plan_id]
        properties:
          plan_id:
            type: string
          approval_override:
            type: boolean
            default: false
    
    steps:
      - id: fetch-promotion-plan
        name: "Fetch Promotion Plan"
        type: service-call
        service: promotion-orchestrator
        action: get_plan
        input:
          plan_id: "{{workflow.input.plan_id}}"
        output:
          promotion_plan: "{{step.result.plan}}"
        timeout: 5s
      
      - id: validate-artifact
        name: "Validate Artifact"
        type: service-call
        service: artifact-registry
        action: validate
        input:
          artifact_id: "{{steps.fetch-promotion-plan.output.promotion_plan.artifact_id}}"
        output:
          artifact_valid: "{{step.result.valid}}"
          artifact_metadata: "{{step.result.metadata}}"
        timeout: 10s
      
      - id: run-pre-promotion-tests
        name: "Run Pre-Promotion Tests"
        type: service-call
        service: validation-service
        action: run_tests
        input:
          artifact_id: "{{steps.fetch-promotion-plan.output.promotion_plan.artifact_id}}"
          test_suite: "pre-promotion"
        output:
          tests_passed: "{{step.result.passed}}"
        timeout: 300s
      
      - id: request-approval
        name: "Request Approval"
        type: conditional
        condition: "{{steps.fetch-promotion-plan.output.promotion_plan.approval_required == true && workflow.input.approval_override == false}}"
        then:
          - type: service-call
            service: approval-service
            action: request
            input:
              promotion_plan: "{{steps.fetch-promotion-plan.output.promotion_plan}}"
              approvers: "{{steps.fetch-promotion-plan.output.promotion_plan.approvers}}"
            output:
              approval_id: "{{step.result.id}}"
          
          - type: wait
            condition: "approval.status == 'approved'"
            timeout: 172800s  # 48 hours
        timeout: 172800s
      
      - id: create-deployment
        name: "Create Deployment"
        type: service-call
        service: deployment-service
        action: create
        input:
          artifact_id: "{{steps.fetch-promotion-plan.output.promotion_plan.artifact_id}}"
          target_environment: "{{steps.fetch-promotion-plan.output.promotion_plan.target_env}}"
          strategy: "{{steps.fetch-promotion-plan.output.promotion_plan.strategy}}"
        output:
          deployment_id: "{{step.result.id}}"
        timeout: 10s
      
      - id: execute-deployment
        name: "Execute Deployment"
        type: service-call
        service: deployment-service
        action: execute
        input:
          deployment_id: "{{steps.create-deployment.output.deployment_id}}"
        output:
          deployment_status: "{{step.result.status}}"
        error_handling:
          on_error: rollback
        timeout: 600s
      
      - id: monitor-health
        name: "Monitor Health"
        type: service-call
        service: health-monitor
        action: monitor
        input:
          deployment_id: "{{steps.create-deployment.output.deployment_id}}"
          duration: 300s
        output:
          health_status: "{{step.result.status}}"
        timeout: 300s
      
      - id: run-smoke-tests
        name: "Run Smoke Tests"
        type: service-call
        service: validation-service
        action: run_tests
        input:
          deployment_id: "{{steps.create-deployment.output.deployment_id}}"
          test_suite: "smoke"
        output:
          smoke_tests_passed: "{{step.result.passed}}"
        timeout: 300s
      
      - id: finalize-promotion
        name: "Finalize Promotion"
        type: conditional
        condition: "{{steps.monitor-health.output.health_status == 'healthy' && steps.run-smoke-tests.output.smoke_tests_passed == true}}"
        then:
          - type: service-call
            service: promotion-orchestrator
            action: finalize
            input:
              promotion_id: "{{workflow.id}}"
              deployment_id: "{{steps.create-deployment.output.deployment_id}}"
            output:
              promotion_status: "completed"
        else:
          - type: service-call
            service: deployment-service
            action: rollback
            input:
              deployment_id: "{{steps.create-deployment.output.deployment_id}}"
            output:
              rollback_status: "{{step.result.status}}"
        timeout: 60s
      
      - id: update-artifact-status
        name: "Update Artifact Status"
        type: service-call
        service: artifact-registry
        action: update_status
        input:
          artifact_id: "{{steps.fetch-promotion-plan.output.promotion_plan.artifact_id}}"
          environment: "{{steps.fetch-promotion-plan.output.promotion_plan.target_env}}"
          status: "promoted"
        timeout: 5s
      
      - id: publish-promotion-event
        name: "Publish Promotion Event"
        type: event
        action: publish
        target:
          type: kafka
          topic: promotion.completed
        payload:
          promotion_id: "{{workflow.id}}"
          artifact_id: "{{steps.fetch-promotion-plan.output.promotion_plan.artifact_id}}"
          target_env: "{{steps.fetch-promotion-plan.output.promotion_plan.target_env}}"
          status: "{{steps.finalize-promotion.output.promotion_status}}"
    
    output:
      schema:
        type: object
        properties:
          promotion_id:
            type: string
          deployment_id:
            type: string
          status:
            type: string
    
    error_handling:
      global:
        on_error: rollback_and_notify
        notify: ["release-team@ninjatech.ai"]

  # Canary Deployment Workflow
  - name: canary-deployment
    description: "Progressive canary deployment"
    type: sequential
    trigger:
      type: api
      endpoint: "/api/v1/promotion/canary"
      method: POST
    
    input:
      schema:
        type: object
        required: [artifact_id, environment]
        properties:
          artifact_id:
            type: string
          environment:
            type: string
          canary_steps:
            type: array
            default: [10, 50, 100]
    
    steps:
      - id: deploy-canary
        name: "Deploy Canary"
        type: loop
        iterator: "{{workflow.input.canary_steps}}"
        steps:
          - id: update-traffic
            type: service-call
            service: deployment-service
            action: update_traffic
            input:
              artifact_id: "{{workflow.input.artifact_id}}"
              environment: "{{workflow.input.environment}}"
              percentage: "{{loop.item}}"
            timeout: 30s
          
          - id: monitor-metrics
            type: service-call
            service: health-monitor
            action: monitor_metrics
            input:
              environment: "{{workflow.input.environment}}"
              duration: 300s
            output:
              metrics: "{{step.result.metrics}}"
            timeout: 300s
          
          - id: evaluate-metrics
            type: service-call
            service: health-monitor
            action: evaluate
            input:
              metrics: "{{steps.monitor-metrics.output.metrics}}"
            output:
              healthy: "{{step.result.healthy}}"
            timeout: 5s
          
          - id: decide-rollback
            type: conditional
            condition: "{{steps.evaluate-metrics.output.healthy == false}}"
            then:
              - type: service-call
                service: deployment-service
                action: rollback
                input:
                  artifact_id: "{{workflow.input.artifact_id}}"
                  environment: "{{workflow.input.environment}}"
              - type: break
    
    output:
      schema:
        type: object
        properties:
          status:
            type: string
          final_percentage:
            type: integer

  # Rollback Workflow
  - name: deployment-rollback
    description: "Rollback failed deployment"
    type: sequential
    trigger:
      type: event
      source: kafka
      topic: deployment.failed
    
    input:
      schema:
        type: object
        required: [deployment_id]
        properties:
          deployment_id:
            type: string
    
    steps:
      - id: fetch-deployment
        name: "Fetch Deployment"
        type: service-call
        service: deployment-service
        action: get
        input:
          deployment_id: "{{workflow.input.deployment_id}}"
        output:
          deployment: "{{step.result.deployment}}"
        timeout: 5s
      
      - id: create-rollback-plan
        name: "Create Rollback Plan"
        type: service-call
        service: deployment-service
        action: create_rollback_plan
        input:
          deployment: "{{steps.fetch-deployment.output.deployment}}"
        output:
          rollback_plan: "{{step.result.plan}}"
        timeout: 10s
      
      - id: execute-rollback
        name: "Execute Rollback"
        type: service-call
        service: deployment-service
        action: execute_rollback
        input:
          rollback_plan: "{{steps.create-rollback-plan.output.rollback_plan}}"
        output:
          rollback_status: "{{step.result.status}}"
        timeout: 300s
      
      - id: verify-rollback
        name: "Verify Rollback"
        type: service-call
        service: health-monitor
        action: verify
        input:
          deployment_id: "{{workflow.input.deployment_id}}"
        output:
          verified: "{{step.result.verified}}"
        timeout: 60s
    
    output:
      schema:
        type: object
        properties:
          rollback_status:
            type: string
          verified:
            type: boolean

error_handling:
  patterns:
    - name: deployment-rollback
      on_failure: automatic_rollback
      notify: true

state_management:
  storage: redis
  ttl: 86400

monitoring:
  metrics:
    - name: promotion_duration
      type: histogram
    - name: deployment_success_rate
      type: counter

documentation:
  workflow_guide: "https://docs.ninjatech.ai/mcp/promotion-engine/workflows"
