# MCP Level 3 - Promotion Engine Policy
# Defines governance policies, access control, and compliance rules

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EnginePolicy
metadata:
  name: promotion-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Promotion Engine Governance and Access Control Policies"
  labels:
    engine-type: promotion
    policy-type: governance
    compliance: required
  annotations:
    mcp.ninjatech.ai/policy-version: "1.0.0"
    mcp.ninjatech.ai/enforcement: "strict"

# ============================================================================
# ROLE-BASED ACCESS CONTROL (RBAC)
# ============================================================================

rbac:
  roles:
    - name: promotion-admin
      description: "Full administrative access"
      permissions:
        - resource: "*"
          actions: ["*"]
      subjects:
        - kind: User
          names: ["admin@ninjatech.ai"]
    
    - name: release-manager
      description: "Manage promotions and deployments"
      permissions:
        - resource: "promotion-plans"
          actions: ["create", "read", "update", "delete"]
        - resource: "promotions"
          actions: ["create", "read", "execute", "rollback"]
        - resource: "approvals"
          actions: ["request", "read"]
        - resource: "deployments"
          actions: ["create", "read", "rollback"]
      subjects:
        - kind: Group
          names: ["release-managers"]
    
    - name: approver
      description: "Approve or reject promotions"
      permissions:
        - resource: "approvals"
          actions: ["read", "approve", "reject"]
        - resource: "promotions"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["approvers", "engineering-leads"]
    
    - name: deployment-operator
      description: "Execute deployments"
      permissions:
        - resource: "deployments"
          actions: ["create", "read", "monitor"]
        - resource: "promotions"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["operators"]
    
    - name: promotion-viewer
      description: "Read-only access"
      permissions:
        - resource: "*"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["viewers"]

authentication:
  methods:
    - type: oauth2
      enabled: true
    - type: api-key
      enabled: true

authorization:
  engine: "opa"
  evaluation:
    mode: "strict"
    deny_by_default: true

# ============================================================================
# PROMOTION POLICIES
# ============================================================================

promotion:
  approval_workflow:
    required_for:
      - environment: "production"
        minimum_approvers: 2
        approver_roles: ["release-manager", "engineering-lead"]
      
      - environment: "staging"
        minimum_approvers: 1
        approver_roles: ["release-manager"]
    
    timeout: 48h
    auto_reject_on_timeout: false
  
  deployment_strategies:
    allowed:
      - blue_green
      - canary
      - rolling
    
    default: rolling
    
    by_environment:
      - environment: "production"
        allowed: [blue_green, canary]
        default: blue_green
      
      - environment: "staging"
        allowed: [rolling, recreate]
        default: rolling
  
  validation:
    pre_promotion:
      - check: "tests_passed"
        required: true
      - check: "security_scan_passed"
        required: true
      - check: "performance_benchmarks_met"
        required: false
    
    post_promotion:
      - check: "health_check_passed"
        required: true
        timeout: 300
      - check: "smoke_tests_passed"
        required: true
        timeout: 600
  
  rollback:
    automatic:
      enabled: true
      triggers:
        - "health_check_failed"
        - "error_rate_exceeded"
        - "latency_threshold_exceeded"
    
    manual:
      allowed_roles: ["release-manager", "promotion-admin"]

security:
  encryption:
    at_rest:
      enabled: true
      algorithm: "AES-256-GCM"
    in_transit:
      enabled: true
      protocol: "TLS 1.3"
  
  artifact_verification:
    enabled: true
    methods:
      - signature_verification
      - checksum_validation
      - vulnerability_scanning

compliance:
  frameworks:
    - name: "SOC2"
      enabled: true
      controls:
        - change_management
        - deployment_tracking
        - rollback_capability
  
  audit:
    enabled: true
    events:
      - "promotion_created"
      - "promotion_executed"
      - "approval_granted"
      - "approval_rejected"
      - "deployment_created"
      - "deployment_rolled_back"
    retention: 365d

enforcement:
  mode: "strict"
  violations:
    - severity: "critical"
      action: "block"
      notify: ["security-team@ninjatech.ai", "release-managers@ninjatech.ai"]

documentation:
  policy_guide: "https://docs.ninjatech.ai/mcp/promotion-engine/policies"