# MCP Level 3 - Taxonomy Engine Policy
# Defines governance policies, access control, and compliance rules

apiVersion: mcp.ninjatech.ai/v1alpha1
kind: EnginePolicy
metadata:
  name: taxonomy-engine
  namespace: mcp-level3
  version: 1.0.0
  description: "Taxonomy Engine Governance and Access Control Policies"
  labels:
    engine-type: taxonomy
    policy-type: governance
    compliance: required
  annotations:
    mcp.ninjatech.ai/policy-version: "1.0.0"
    mcp.ninjatech.ai/enforcement: "strict"

# ============================================================================
# ROLE-BASED ACCESS CONTROL (RBAC)
# ============================================================================

rbac:
  roles:
    - name: taxonomy-admin
      description: "Full administrative access"
      permissions:
        - resource: "*"
          actions: ["*"]
      subjects:
        - kind: User
          names: ["admin@ninjatech.ai"]
    
    - name: taxonomy-curator
      description: "Manage taxonomies and entities"
      permissions:
        - resource: "taxonomies"
          actions: ["create", "read", "update", "delete"]
        - resource: "entities"
          actions: ["create", "read", "update", "delete"]
        - resource: "relationships"
          actions: ["create", "read", "delete"]
      subjects:
        - kind: Group
          names: ["curators", "knowledge-engineers"]
    
    - name: taxonomy-contributor
      description: "Add and edit entities"
      permissions:
        - resource: "entities"
          actions: ["create", "read", "update"]
        - resource: "relationships"
          actions: ["create", "read"]
      subjects:
        - kind: Group
          names: ["contributors"]
    
    - name: taxonomy-viewer
      description: "Read-only access"
      permissions:
        - resource: "*"
          actions: ["read"]
      subjects:
        - kind: Group
          names: ["viewers"]

authentication:
  methods:
    - type: oauth2
      enabled: true
    - type: api-key
      enabled: true

authorization:
  engine: "opa"
  evaluation:
    mode: "strict"
    deny_by_default: true

# ============================================================================
# DATA GOVERNANCE
# ============================================================================

data_governance:
  quality:
    validation:
      - rule: "entity_name_required"
        condition: "len(entity.name) > 0"
        severity: "error"
      
      - rule: "relationship_validity"
        condition: "exists(source) AND exists(target)"
        severity: "error"
  
  versioning:
    enabled: true
    retention: 90d

security:
  encryption:
    at_rest:
      enabled: true
      algorithm: "AES-256-GCM"
    in_transit:
      enabled: true
      protocol: "TLS 1.3"

compliance:
  frameworks:
    - name: "SOC2"
      enabled: true
  
  audit:
    enabled: true
    retention: 365d

enforcement:
  mode: "strict"
  violations:
    - severity: "critical"
      action: "block"

documentation:
  policy_guide: "https://docs.ninjatech.ai/mcp/taxonomy-engine/policies"